# `Нейронные сети и компьютерное зрение`

[Презентации GitHub](https://github.com/NazarovMichail/NN-CV-presentations)

[Ноутбуки GitHub](https://github.com/NazarovMichail/NN-CV)

___
## <center> <a>$\boxed{\text{Нейрон и нейронная сеть}}$</a>

___
### <a> Схема нейрона</a>

<img src='img/neuron.png'>

- `Разделяющая поверхность` - это геометрическое место точек, где функция активации меняет свое значение 

- Разделяющая поверхность задается формулой :

    - $<\vec{x}, \vec{w}> + b = 0$

        - Вектор $\vec{w}$ является нормалью к гиперплоскости, которая задана этим уравнением

<img src='img/surface.png' width=300>

___
### <a>Функция активации</a>

`Функция активации` - `дифференцируемая` функция, применяемая к линейному преобразованию для создания `нелинейного` преобразования признаков и аппроксимации `нелинейных зависимостей` в данных

<img src='img/func.png' width=700>

- `Пороговая` функция активации всегда будет равна 1 с той стороны от разделяющей прямой, в которую указывает вектор $\vec{w}$

`Производная` функции активации :

- `Сигмоида` 
    - $\boxed { \sigma(\vec{w}) = \frac{1}{1 - e^{-\vec{w}}} }$ : 

        - $\boxed{\frac{\delta \sigma(\vec{w})}{\delta \vec{w} } = \sigma(\vec{w}) \cdot (1 - \sigma(\vec{w})) }$

- `Гиперболический тангенс` 
    - $\boxed{ th(\vec{w}) = \frac{e^{\vec{w} } - e^{- \vec{ w} }}  {e^{\vec{w} } + e^{-\vec{w} }  } }$ :

        - $\boxed{\frac{\delta th(\vec{w})}{\delta \vec{w} } = 1 - th(\vec{w}) ^2 }$

___
### <a>Правило цепочки</a>

`Правило дифференцирования` сложной функции :

<img src='img/rule.png'>

Для функции потерь :

$L\Bigg( f_4\bigg(f_2(f_1(x)), f_3(f_1(x))\bigg) \Bigg) $

`Граф` вычисления :

<img src='img/chain.png'>

`Производная функции потерь` по параметрам модели :

$\boxed{ \frac{\delta L}{\delta w_1} = \frac{\delta L}{\delta y_4} \cdot \bigg[ \frac{\delta f_4}{\delta y_2} \cdot \frac{\delta f_2}{\delta y_1} + \frac{\delta f_4}{\delta y_3} \cdot \frac{\delta f_3}{\delta y_1}\bigg] \cdot \frac{\delta f_1}{\delta w_1} }$




___
#### <a style='color:grey'>Пример (правило цепочки)</a>

____

- Записать математическое выражение, которое задает граф :

    - $x_i$ : входы в граф

    - $b_i, c_i$ : настраиваемые параметры

<img src='img/forw_t1.png' width=400>

$\boxed{ y = ((x_1+b_1) * \sigma(x_2+b_2))*c_1 + \sigma(x_1+b_1) * \tanh(x_2+b_2) * c_2 }$

___

- Найти производную $y$ по параметру $c_2$ :
​
 
<img src='img/back_t1.png' width=400>

$\boxed{ \frac{\delta y}{\delta c_2} = \frac{\delta y}{\delta z_9} \cdot \frac{\delta z_9}{\delta z_6} \cdot \frac{\delta z_6}{\delta c_2} }$


___

- Найти производную $y$ по параметру $b_1$ :
​
 
<img src='img/back_t1.png' width=400>

$\boxed{ \frac{\delta y}{\delta b_1} = (\frac{\delta y}{\delta z_9} \cdot \frac{\delta z_9}{\delta z_3} \cdot\frac{\delta z_3}{\delta z_1} + \frac{\delta y}{\delta z_8} \cdot \frac{\delta z_8}{\delta z_7} \cdot\frac{\delta z_7}{\delta z_1}) \cdot \frac{\delta z_1}{\delta b_1} } $

___

- Найти производную $y$ по параметру $b_2$ :
​
 
<img src='img/back_t1.png' width=400>

$\boxed{ \frac{\delta y}{\delta b_2} = (\frac{\delta y}{\delta z_8} \cdot \frac{\delta z_8}{\delta z_7} \cdot\frac{\delta z_7}{\delta z_4} \cdot\frac{\delta z_4}{\delta z_2} + \frac{\delta y}{\delta z_9} \cdot \frac{\delta z_9}{\delta z_6} \cdot\frac{\delta z_6}{\delta z_5} \cdot\frac{\delta z_5}{\delta z_2}) \cdot \frac{\delta z_2}{\delta b_2} } $

___

- Найти производную $y$ по  $c_2$, выраженную через `входные параметры` $x_i, b_i$ :
 
<img src='img/back_t1.png' width=400>

$\boxed{ \frac{\delta y}{\delta c_2} =  \frac{\delta y}{\delta z_9}\cdot \frac{\delta z_9}{\delta z_6} \cdot \frac{\delta z_6}{\delta c_2}} $ :

$\boxed{1}$ 
- $\boxed{ \frac{\delta y}{\delta z_9}} = \frac{\delta (z_9 + z_8)}{\delta z_9} = \boxed {1}$

$\boxed{2}$ 
- $\boxed{ \frac{\delta z_9}{\delta z_6}} = \frac{\delta (z_3 \cdot z_6)}{\delta z_6} = z_3$

    - $z_3 = \sigma(z_1) = \boxed{\sigma(x_1 + b_1)}$


$\boxed{3}$ 

- $\boxed{ \frac{\delta z_6}{\delta c_2}} = \frac{\delta (z_5 \cdot z_2)}{\delta z_2} = z_5$

    - $z_5 = \tanh(z_2) =  \boxed{\tanh(x_2 + b_2)}$

$\boxed{ \frac{\delta y}{\delta c_2} = 1 \cdot \sigma(x_1 + b_1) \cdot  \tanh(x_2 + b_2)} $

___
## <center> <a>$\boxed{\text{Задачи ИНС}}$</a>

___
### <a>Бинарная классификация</a>

`Функция потерь: Бинарная кросс-энтропия`

$\boxed{BCE(y, \sigma(x)) = - y \cdot \ln \sigma(x) - \big(1- y\big) \cdot \big(1 - \ln \sigma(x)\big) }$
- $\sigma(x)$ : выход сети, интерпретируемый как вероятность класса
- $y$: действительный класс объекта

`Градиент`

$\frac{\delta BCE(y, \sigma(x))}{\delta x } = \frac{\delta BCE(y, \sigma(x))}{\sigma(x) } \cdot  \frac{\sigma(x)}{x } $

- $\boxed{\frac{\delta BCE(y, \sigma(x))}{\delta x } = \sigma(x) - y }$

___
### <a>Мультиклассовая классификация</a>

`Функция активации: Софтмакс`

$\boxed{SM(y)_i =\frac{e^{y_i}}{\sum_{j=1}^n e^{y_j}}}$

- $y_i$: выход сети, как любое действительное число
- $\sum_{j=1}^n e^{y_j}$: сумма всех экспонент выходов сети, как вероятности классов

`Градиент`

$\boxed{\frac{\delta SM(y_i)}{\delta y_c } = - SM(y_i) \cdot SM(y_c) }$

$\boxed{\frac{\delta SM(y_i)}{\delta y_i } =  SM(y_i) \cdot \big(1 - SM(y_i)\big) }$

- $y_c$: выход не целевого объекта, как любое действительное число
- $y_i$: выход целевого объекта, как любое действительное число

`Функция потерь: Кросс-энтропия`

$\boxed{CE(t, SM) = - \sum_{c=1}^n t_c \cdot \ln SM_c }$

- $t_c$: таргетное значение для класса
- $SM_c$: софтмакс для выходов сети

`Градиент`

$\boxed{\frac{\delta CE}{\delta y_i } = - t_i +  SM_i}$


___
### <a>Детекция</a>

<img src='img/detect.png'>

`Центр объекта`

$X_c \in [0, 1 ]$, что является `областью значений сигмоиды`
- 0 : левый нижний угол всего изображения
- 1 : правый нижниый угол всего изображения

$Y_c \in [0, 1 ]$, что является `областью значений сигмоиды`
- 0 : левый нижний угол всего изображения
- 1 : левый верхний угол всего изображения

`Высота и ширина объекта`

$w \in [0, +\infty ]$: , что является `областью значений экспоненты`

$h \in [0, +\infty ]$: , что является `областью значений экспоненты`

`Функция потерь`

- $\boxed{BCE( \sigma (z_0), I) }$: бинарная кросс-энтропия для выходов вероятностей классов 
    - $I$: индикатор, есть ли целевой объект на изображении
- $\boxed{ I \cdot \Big(BCE( \sigma (z_1), x_c) + BCE( \sigma (z_2), y_c) \Big) }$: бинарная кросс-энтропия для выходов центра объекта

- $\boxed{MSE(z_3, \ln w) }$, т.к.
    - $\hat{w} = e^{z_3}$: ширина выданная сетью
    - $t_3 = \ln w$: теоретический выход, необходимый, для того, чтобы получить таргет-ширину
        - $MSE(z_3, t_3)$, сравниваются теоретический и практический выходы сети, вне зависимости абсолютного значения ширины, во сколько раз практическая ширина меньше или больше теоретической

___
### <a>Сегментация</a>

<img src='img/segment.png'>

`Теоретическое` значение пикселей 
- Значение пикселя относящегося к объекту: 1
- Значение пикселя не относящегося к объекту: 0

`Практическое` значение пикселей 
- Вероятность того, что пиксель относится к объекту $\in [0, 1 ]$

___
### <a>Сжатие размерности</a>

<img src='img/autoenc.png'>

- `Кодировщик` преобразует изображение в сжатое представление (эмбеддинг)
    - Кол-во параметров сильно меньше, чем в исходном представлении, что является обобщением информации

- `Декодировщик` обратно преобразует  изображение в исходное состояние

- `Функция потерь` сравнивает исходное изображение и полученное после декодирования

___
### <a>Увеличение размерности</a>

<img src='img/super.png'>


- `Исходное` изображение в вымоком разрешении `уменьшается` в размерности
- Изображение с `уменьшенной` размерность подается на `вход` сети
- Изображение на `выходе` сравнивается с `исходным` изображением


___
## <center> <a>$\boxed{\text{Методы оптимизации}}$</a>

___
### <a>Градиентный спуск</a>

<img src='img/gd.png'>

- Изменение весов `всех объектов` на каждой итерации

___
### <a>Стохастический градиентный спуск</a>

<img src='img/sgd.png'>

- Изменение весов `одного объекта` на каждой итерации

___
### <a>Стохастический градиентный спуск с импульсом</a>

- Вдоль направления, на котором градиент меняет знак сумма градиентов будет уменьшаться
- Вдоль направления, на котором градиент не меняет знак сумма градиентов будет увеличиаться
<img src='img/moment0.png'>

- $\alpha$ : шаг обучения
- $\beta$ : коэффициент импульса


___
### <a>RMSprop</a>

- Если производная по некоторому направлению `большая`, то RMSprop `замедляет` скорость обучения по этому направлению
- Если производная по некоторому направлению `маленькая`, то RMSprop `ускоряет` скорость обучения по этому направлению

<img src='img/rmsprop.png'>

- $\alpha$ : шаг обучения
- $\nabla L$ : градиент по всем весам 
- $EMA_\beta^t(\nabla L)$: экспоненциальное скользящее среднее от квадрата градиента функции потерь в текущий момент времени
    - больший вес придается последним данным
    - вес регулируется параметром $\beta$

___
### <a>Adam</a>

- В отличие от RMSprop оптимизируется градиент экспоненциального скользящего  среднего (в числителе)

<img src='img/adam.png'>

Оптимальные параметры:
- $\alpha = 3 \cdot 10^{-4}$ 
- $\beta_1 = 0.9$ 
- $\beta_2 = 0.999$ 

___
## <center> <a>$\boxed{\text{Сверточные нейронные сети}}$</a>

___
### <a>Двумерная свертка</a>

`Сумма` `поэлементного` `умножения` ядра на матрицу
<img src='img/conv2d.png' width=500>
- Stride = 1
- Padding = 1
___

<img src='img/conv2d2.png' width=500>

- Stride = 2
- Padding = 1
___

`Numpy`

In [40]:
import numpy as np

a = np.array([[4, 2, -1],[-6, 0, 5],[3, 2, 2]])
kernel = np.array([[0, 1, 2],[1, -1, 0],[1, 0, -2]])

In [41]:
a_pad = np.pad(a, pad_width=1)

In [42]:
a_pad_1 = a_pad[:3, :3]
a_pad_2 = a_pad[:3, 2:]
a_pad_3 = a_pad[2:, :3]
a_pad_4 = a_pad[2:, 2:]

In [43]:
conv_2 = np.array(
[
[np.sum(a_pad_1 * kernel)],
[np.sum(a_pad_2 * kernel)],
[np.sum(a_pad_3 * kernel)],
[np.sum(a_pad_4 * kernel)],
    ]
    )
conv_2.reshape(2,2)

array([[-4,  3],
       [-9,  5]])

`Pytorch`

In [45]:
import torch

a = torch.tensor([[4, 2, -1],[-6, 0, 5],[3, 2, 2]], dtype=torch.float32).reshape(1,1,3,3)
kernel = torch.tensor([[0, 1, 2],[1, -1, 0],[1, 0, -2]], dtype=torch.float32).reshape(1,1,3,3)

torch.conv2d(a, stride=2, padding=1, weight=kernel)

tensor([[[[-4.,  3.],
          [-9.,  5.]]]])

___
### <a>Многомерная свертка</a>


<img src='img/conv3d1.png' width=500>

- Для каждого канал может применяться свое ядро
___
<img src='img/conv3d2.png' width=500>

- $M$: кол-во каналов на выходе равно кол-ву прмененных ядер
 

___
### <a>Пулинг</a>

Позволяет экономить `память`

<img src='img/pool.png' width=500>

Виды пулинга:
- MaxPool
- AvgPool
- MinPool

In [65]:
a = torch.arange(1, 17, dtype=torch.float32).reshape(1,4,4)
max_pool = torch.max_pool2d(a, kernel_size=2)
print(a)
print(max_pool)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]])
tensor([[[ 6.,  8.],
         [14., 16.]]])


___
## <center> <a>$\boxed{\text{Архитектуры сверточных нейронных сетей}}$</a>

___
### <a>LeNet</a>

Создана для решения задачи `MNIST`

- `Первый блок`

<img src='img/lenet1.png' width=400>

- `Архитектура LeNet`

<img src='img/lenet2.png' width=700>

- Функция активации `Tanh`


___
### <a>AlexNet</a>

Создана для решения задачи `ImageNet`

- `Архитектура AlexNet`

<img src='img/alexnet.png' width=700>

- Функция активации `Relu`
- Последние 2 светки - каскад сверток 3 $\times$ 3 и 3 $\times$ 3, заменяющий свертку 5 $\times$ 5, но использующие меньше параметров:
    - $5 \cdot 5  + 1(bias) = 26$
    - $3 \cdot 3 + 3 \cdot 3 + 2(bias) = 20$
    - <img src='img/cascade.png' width=400></img>
        - Слева область свертки 5 $\times$ 5
        - Справа голубая область свертки 3 $\times$ 3 как результат предыдущей свертки 3 $\times$ 3 (оранжевая)


___
### <a>VGG</a>

- `Архитектура AlexNet`

<img src='img/vgg.png' width=700>

- Используются `каскады сверток` для оптимизации количества параметров
- В `процессе обучения` к исходной сети `A` добавляются слои:
    - `B`: conv3-64, conv3-128
    - `C`: conv1-256, conv1-512, conv1-512
    - ...

___
### <a>GoogleNet</a>

<img src='img/googlenet.png' width=900></img>

- `Inseption block`:

<img src='img/incept.png' width=500>

- В блоке `параллельно` выполняются различные виды сверток и затем `конкатенируются`
    - Свертка 1 $\times$ 1 ( `bottle neck` ) пердобрабатывает входные каналы и уменьшает или увеличивает число каналов 
        - <img src='img/bottle.png' width=600></img>

- Доболнительные выходы с `функциями потерь` помогают устранять `затухание` градиента


___
### <a>ResNet</a>

Из-за большой глубины и Avg pooling вконце обучения,  ResNet `может принимать изображения любого размера` (кратные 32)

<img src='img/resnet.png' width=900></img>

- `Residual block`

<img src='img/rb.png' width=600></img>

- Т.к. результат выхода из Residual block - $\boxed{f(x) + x }$, то
    -  $(f(x) + x )'$ = $\boxed{f'(x) + 1 }$,
    -  что добавляет 1 к градиенту и устраняет затухание градиента при обратном распространении

- В конце после сверточных слоев производится `Avg polling`, превращая выход в `вектор` с размером 1 $\times$ C, где
    - С: кол-во каналов



___
### <a>DenseNet</a>

<img src='img/dense.png' width=900></img>

___
### <a>SENet</a>

<img src='img/senet.png' width=900></img>

___
## <center> <a>$\boxed{\text{Регуляризация и нормализация}}$</a>

___
### <a>Early stopping</a>

Обучение модели необходимо `остановить`, когда ошибка на `проверочном` наборе данных перестаёт `уменьшаться`. Это может быть признаком того, что модель начинает запоминать шум в данных, а не обобщать их.

<img src='img/estop.png' width=600></img>


___
### <a>Регуляризация Ridge</a>

К функции потерь добавляется дополнительный штраф за `большие значения весов`, как `сумма квадратов весов`

$\boxed{ L = \sum_{s=0}^s \Big(\sum_{i=1}^{n} w_i \cdot x_i - y_s \Big)^2 + \lambda \cdot \sum_{j=1}^j w^2_j }$

<img src='img/reg1.png' width=400></img>

- Увеличение значения коэффициента регулеризации $\lambda$ сглаживает пики аппроксимирующей функции

Объяснение работы L2-регуляризации:

<img src='img/ridge.png' width=400></img>

- Слева линии уровня значения функции потерь для значений весов $w_1$ и $w_2$
- Справа окружности - максимумы значений весов $w_1$ и $w_2$ при регуляризации, т.к. 
    - $w_1^2 + w_2^2 = R^2$ : уравнение окружности

- Чем `больше` $\lambda$, тем `больше` влияние регуляризации и `меньше` окружность
    - Значения весов стягиваются к миниимальным значениям,
    - Значение функции потерь увеличивается


___
### <a>Регуляризация Lasso</a>

К функции потерь добавляется дополнительный штраф за `большие значения весов`, как `сумма модулей весов`

$\boxed{ L = \sum_{s=0}^s \Big(\sum_{i=1}^{n} w_i \cdot x_i - y_s \Big)^2 + \lambda \cdot \sum_{j=1}^j | w_j | }$

<img src='img/lasso.png' width=500></img>

- Есть высокая вероятность `занулить` некоторые веса, т.к. `наибольшие` значения весов лежат на `осях`


___
### <a>DropOut</a>

На каждой итерации обучения случайно выбранные нейроны (или связи между ними) временно `исключаются` из процесса.  
Это помогает предотвратить запоминание сетью ненужных деталей и повышает её обобщающую способность.


Drop `connection`:

<img src='img/doc.png' width=200></img>

Drop `neuron`:

<img src='img/don.png' width=200></img>


___
### <a>Нормализация</a>

$\boxed{ x_{stand} = \frac{ x_i - \mu}{\sigma} }$, где

- $\boxed{ \mu = \frac{ \sum_{i=1}^n x_i }{n} }$: среднее значение

- $\boxed{ \sigma = \sqrt{\frac{ \sum_{i=1}^n (x_i - \mu)^2 }{n - 1}} }$: стандартное отклонение


Процесс приведения входных данных к определённому диапазону значений.  
Нормализация позволяет:
- улучшить производительность
- улучшить стабильность модели
- ускорить процесс обучения.


`Центрирование` упрощает подбор весов, т.к. размещает данные ближе к 0 значениям

<img src='img/cener.png' width=500></img>

- Стандартизация позволяет весам признаков вносить одинаковый вклад в функцию потерь,
    - Функция потерь принимает округлую форму вместо вытянутой, 
        - что упрощает поиск минимума при помощи градиентного спуска

<img src='img/std.png' width=500></img>


___
### <a>BatchNorm</a>

Нормализация данных после каждого слоя сети для каждого батча 

$\boxed{ x_{stand}^{batch} = \frac{ x_i - \mu_{batch}}{\sigma_{batch}} \cdot \gamma + \beta }$, где

- $\gamma$ : обучаемый вектор размера входящих данных, вносящий смещение в стандартное отклонение
- $\beta$ : обучаемый вектор размера входящих данных, вносящий смещение в среднее значение

На инференсе $\mu$ и $\sigma$ принимаются как значения скользящего экспоненциального среднего по $\mu_{batch}$ и $\sigma_{batch}$

При обучении нельзя использовать значения скользящего экспоненциального среднего по $\mu_{batch}$ и $\sigma_{batch}$ т.к. проблемно высчитать производную на обратном ходе.

In [94]:
import torch
import torch.nn as nn

def custom_batch_norm1d(input_tensor, eps):
    normed_tensor = (input_tensor - input_tensor.mean(dim=0, keepdim=True)) / (torch.sqrt(input_tensor.var(dim=0, keepdim=True, unbiased=False)+ eps) )
    return normed_tensor

input_tensor = torch.Tensor([[0.0, 0, 1, 0, 2], [0, 1, 1, 0, 10]])
batch_norm = nn.BatchNorm1d(input_tensor.shape[1], affine=False)

custom_batch_norm1d(input_tensor, eps=1e-05) 

tensor([[ 0.0000, -1.0000,  0.0000,  0.0000, -1.0000],
        [ 0.0000,  1.0000,  0.0000,  0.0000,  1.0000]])

- Данные нормируются по `признакам`, а не по объектам
___

___
## <center> <a>$\boxed{\text{Метод максимального правдоподобия}}$</a>

Метод максимального правдоподобия помогает получать `функции потерь` для данных с `различным распределением`

$\boxed{1}$ Вероятность `полного набора набдюдений`:
- $\boxed{ P_X = p_w(x_0) \cdot p_w(x_1) ... p_w(x_i)}$, где
    - $x_0$: `независимое` наблюдение с `одинаковой` функцией рапредления
    - $w$: ненаблюдаемые параметры распределения

$\boxed{2}$ Для того, чтобы получить `максимальные значения вероятности` полного набора данных необходимо `подбирать параметры` $w$, при которых веротность имеет максимальное значение.

- $\boxed{ w = argmax (P_X)}$

$\boxed{3}$ `Максимизацию произведения`вероятностей можно упростить `максимизацией суммы`логарифмов вероятностей, т.к логарифм - монотонно возрастающая функция:

- $\boxed{ w = argmax (\log P_X)}$:

    - $\boxed{ \log P_X = \log p_w(x_0) + \log  p_w(x_1) +...+ \log  p_w(x_i)}$

$\boxed{4}$ Если наблюдения из нормального распределения, то `вероятность отдельного наблюдения`:

- $\boxed{ p_w(x_i) = \frac{1}{\sqrt{2 \pi \sigma^2} } \cdot e^{-\frac{(x_i - \mu)^2}{2 \sigma^2}}}$

$\boxed{5}$ Сумма логарифмов вероятностей наблюдений, которую нужно `максимизировать`, отбрасывая параметры `не влияющие на максимизацию`, сводится к:

- $\boxed{argmax (\log P_X) =  -\sum_{i=1}^N (x_i - \mu)^2}$

    - $\boxed{argmin (\log P_X) =  \sum_{i=1}^N (x_i - \mu)^2}$
