
#  <a id=s>Линейная алгебра
<img src='img/1.gif' width=800>


## <a id=cont>Содержание</a>
- [Операции над матрицами](#1)
- [Свойство матриц](#2)
- [Обратные и транспонированные матрицы](#3)
- [Система линенйных уравнений(СЛАУ)](#4)
- [Элементарные преобразования](#5)
- [Решение СЛАУ](#6)
- [Линейная независимость векторов](#7)
- [Базис и ранг матрицы](#8)
- [Изменение базиса](#9)
- [Изменение базисов в разных линейных пространствах](#10)
- [Образ и ядро](#11)
- [Аффинное пространство](#12)
- [Норма векторного пространства](#13)
- [Симметричные, положительно определенные матрицы](#14)
- [Углы и ортогональность](#15)
- [Ортогональное дополнение](#16)
- [Проекция на прямую](#17)
- [Проекция на подпространство](#18)
- [Ортогонализация Грама-Шмидта](#19)
- [Проекция на афинное пространство](#20)
- [Поворот системы координат](#21)
- [Детерминант](#22)
- [След матрицы](#23)
- [Собственные значения и собственные векторы](#24)
- [Разложение Холецкого](#25)
- [Собственное разложение и диагонализация](#26)
- [Сингулярное разложение (SVD разложение)](#27)
- [Взаимосвязь и отличния Собственного разложенеия и Сингулярного разложения](#28)
- [Матричное приближение](#29)
- [Типы матриц](#30)




____
## <a id=1>Операции над матрицами</a>

In [1]:
import numpy as np

A = np.arange(9).reshape(3,3)
B = np.arange(6).reshape(3,2)
A, '________________',B

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 '________________',
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [2]:
col_sum = np.einsum('ji->i', A)
row_sum = np.einsum('ij->i', A)
diag_sum = np.einsum('ii', A)
diag_arr = np.einsum('ii -> i', A)
trans = np.einsum('ji', A)
mult_sum = np.einsum('ij,ij', A, A)

print(f'Сумма столбцов: {col_sum}')
print(f'Сумма строк: {row_sum}')
print(f'Сумма диагонали: {diag_sum}')
print(f'Массив из диагонали: {diag_arr}')
print(f'Транспонирование: \n {trans}')
print(f'Поэлементное умножение и суммирование: {mult_sum}')

Сумма столбцов: [ 9 12 15]
Сумма строк: [ 3 12 21]
Сумма диагонали: 12
Массив из диагонали: [0 4 8]
Транспонирование: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Поэлементное умножение и суммирование: 204


____
## <a id=2>Свойство матриц</a>


`Ассоциативность`: $(A\cdot B)\cdot C = A\cdot (B\cdot C)$

`Дистибутивность`: $(A + B) \cdot C = A\cdot C + B\cdot C$

`Умножение на единичную матрицу`: $ A \cdot I =  I \cdot A = A $

____
## <a id=3>Обратные и транспонированные матрицы</a>

$A \cdot A^{-1} = A^{-1} \cdot A =I$,  
где $A^{-1}$ - обратная матрица матрице A

`Вычисление обратной матрицы`:

$[A|I] = [I|A^{-1}]$

$[A|I] = \left( \begin  {matrix}
1 & 0 & 2 & 0 & \\ 
1 & 1 & 0 & 0 & \\
1 & 2 & 0 & 1 & \\
1 & 1 & 1 & 1 & \\
\end{matrix} 
\left|
\begin{matrix}
1 & 0 & 0 & 0 & \\ 
0 & 1 & 0 & 0 & \\
0 & 0 & 1 & 0 & \\
0 & 0 & 0 & 1 & \\
\end{matrix} \right. \right )$

Приводим общую матрицу в ступенчатый вид:

$[I|A^{-1}] = \left( \begin  {matrix}
1 & 0 & 0 & 0 & \\ 
0 & 1 & 0 & 0 & \\
0 & 0 & 1 & 0 & \\
0 & 0 & 0 & 1 & \\
\end{matrix} 
\left|
\begin{matrix}
-1 & 2 & -2 & 2 & \\ 
1 & -1 & 2 & -2 & \\
1 & -1 & 1 & -1 & \\
-1 & 0 & -1 & 2 & \\
\end{matrix} \right. \right )$



In [3]:
A = np.array(((1,0,2,0),(1,1,0,0),(1,2,0,1),(1,1,1,1)))
B = np.linalg.inv(A)

print(f'Обратная: \n {B}')
print(f'Единичная: \n {np.round(A @ B)}')
print(f'Единичная: \n {np.round(B @ A)}')

Обратная: 
 [[-1.  2. -2.  2.]
 [ 1. -1.  2. -2.]
 [ 1. -1.  1. -1.]
 [-1.  0. -1.  2.]]
Единичная: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Единичная: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


___
`Свойства обратных матриц`


- $ (A + B) ^{-1} = A^{-1} + B^{-1}  $
- $ (A \cdot B) ^{-1} = B^{-1} \cdot A^{-1} $

`Свойства транспонирования`

- $ (A^T)^T = A $
- $ (A + B) ^{T} = A^{T} + B^{T} $
- $ (A \cdot B) ^{T} = B^{T} \cdot A^{T} $

____
## <a id=4>Система линенйных уравнений(СЛАУ)</a>

В СЛАУ с `двумя` переменными:  
Решение:
- `решения нет` : линии $||$
- `прямая` : описывают одну и ту же линию
- `точка` : пересекаются


$\begin  {matrix} -1x + 1y =1 \\ 
2x + 1y = 4 \end{matrix}$

Решение - точка пересечения двух прямых (1, 2)

<img src='img/slau.png' width=300>

In [4]:
import numpy as np

A = np.array(((-1,1),(2,1)))
B = np.array((1,4))
np.linalg.solve(A,B)

array([1., 2.])

___
В СЛАУ с `тремя` переменными:  
- `решения нет` : если плоскости $||$ 

In [5]:
A = np.array(((1,1,1),(1,-1,2),(2,0,3)))
B = np.array((3,2,1))
try:
    np.linalg.solve(A,B)
except Exception:
    print('СЛАУ не имеет решения, плоскости параллельны')

СЛАУ не имеет решения, плоскости параллельны


- `точка` : если пересекаются все 3 плоскости

In [6]:
A = np.array(((1,1,1),(1,-1,2),(0,1,3)))
B = np.array((3,2,4))
np.linalg.solve(A,B)

array([1., 1., 1.])

- `прямая с бесконечным кол-вом решений` : если пересекаются 2 плоскости из 3 ( 2 плоскости из 3 параллельны )

In [7]:
A = np.array(((1,1,1),(1,-1,2),(2,0,3)))
B = np.array((3,2,5))
try:
    np.linalg.solve(A,B)
except Exception:
    print('СЛАУ имеет бесконечное кол-во решений')

СЛАУ имеет бесконечное кол-во решений


- `плоскость` : если все уравнения описывают одну и ту же плоскость 

____
## <a id=5>Элементарные преобразования</a>
- Перестановка строк матрицы
- Умножение строки на постоянную
- Сложение строк

____
### <a id=6>Решение СЛАУ</a>
___
`Если` $A \cdot x = 0$

- Матрица должна быть преведена к ступенчатому виду, с `ведущими 1`, столбцы с ведущими 1 должны состоять из `0` и ведущих `1`.:  

$A = \begin  {pmatrix}
1 & 3 &0 &0 &3 \\ 
0 & 0 &1 &0 &9\\
0 & 0 &0 &1 &-4\\
\end{pmatrix} = \begin  {pmatrix}0\\0\\0\\ \end{pmatrix}$

- Матрица расширяется до `квадратной`, чтобы по диагонали были или `1` или `-1`:

$\begin  {pmatrix}
1 & 3 &0 &0 &3 \\ 
0 & -1 &0 &0 &0\\
0 & 0 &1 &0 &9\\
0 & 0 &0 &1 &-4\\
0 & 0 &0 &0 &-1\\
\end{pmatrix}$

- Решение уравнения $A \cdot x = 0$ - столбцы `содержащие -1`:

$x = \lambda_1 \begin  {pmatrix}3\\-1\\0\\0\\0\\  \end{pmatrix} + \lambda_2 \begin  {pmatrix}3\\0\\9\\-4\\-1\\  \end{pmatrix}$, где

$\lambda$ : любые действительные числа
___
`Если` $A \cdot x = B$

`Для квадратных матриц`: 

- $A \cdot x = B $

Получаем $I$ слева:

- $A^{-1}\cdot A \cdot x = A^{-1} \cdot B $

- $I \cdot x = A^{-1} \cdot B $
 
- $ x = A^{-1} \cdot B $

`Для неквадратных матриц`:

- $A \cdot x = B $

Получаем квадратную матрицу $A^{T}\cdot A $
 
- $A^{T}\cdot A \cdot x = A^{T} \cdot B $

- $(A^{T}\cdot A)^{-1}\cdot A^{T}\cdot A \cdot x = (A^{T}\cdot A)^{-1}\cdot A^{T} \cdot B $

Т.к. $(A^{T}\cdot A)^{-1}\cdot A^{T}\cdot A = I$ 

- $ x  = (A^{T}\cdot A)^{-1}\cdot A^{T} \cdot B $

$(A^{T}\cdot A)^{-1}\cdot A^{T}$ - `псевдообратная матрица Мура - Пенроуза`






____
## <a id=7>Линейная независимость векторов</a>

Векторы линенйо `зависимы`, если:  
 $\sum \lambda_i x_i = 0$, при как минимум одном $\lambda \neq 0$

Векторы линенйо `независимы`, если:   
$\sum \lambda_i x_i \neq 0$, при как минимум одном $\lambda \neq 0$


____
## <a id=8>Базис и ранг матрицы</a>

`Порождающее множество векторов` - множество векторов, через которые можно описать `любой вектор` линейного пространства.

`Оболочка` - множество всех линейных комбинация векторов из порождающего множества.

$V = span[A]$: оболочка $A$ охватывает все линейное пространство $V$

`Базис`:
- минимальное порождающее множество векторов и максимальное линейно независимое множество векторов.  
- линейно независимые векторы оболочки

У линейного пространства может быть `много базисов`, но `количество векторов` в базисах постоянно.

`Размерность` линейного пространства - кол-во базисных векторов. (кол-во независимых направлений).

Если $Y$ - подпространство линейного пространства $V$,то  
 $dim(Y) \leq dim(V)$

`Ранг` - кол-во линейно независимых столбцов и строк матрицы.

Свойства `ранга`:
- $rk(A) = rk(A^T)$
- `Образ` - подпространство Y c $dim(Y)=rk(A)$, которое охватывают столбцы матрицы $A$
- $A^{n \times n}$ `обратимая`, если $rank(A) = n$
- СЛАУ $A\cdot x = b$ `имеет решение`, только для $rk(A) = rk(A|b)$
- `Ядро` - подпространство решений $A^{m \times n}\cdot x = 0$, для которого   
$dim(ker(A))= n-rk(A)$

In [8]:
A = np.array(((2,6,1), (0,1,4), (-8,-24,-4)))
rank = np.linalg.matrix_rank(A)
print(f'Ранг матрицы \n {A} \n -> {rank}')

Ранг матрицы 
 [[  2   6   1]
 [  0   1   4]
 [ -8 -24  -4]] 
 -> 2


____
## <a id=9>Изменение базиса</a>
`Матрица перехода` от старого базиса к новому ( $A_{e\rightarrow f}$ ) - матрица, в которой
- `столбцы`: координаты нового базиса ($f$) выражаются через исходные координаты ($e$),   

при умножении которой на координатный вектор в исходных координатах ( $\hat{v_e}$ ),  
получается координатный вектор $\hat{v}_{e\rightarrow f}$ который:
- смещается пропорционально новым базисам
- координаты выражаются через исходные координаты

$A_{e\rightarrow f} \cdot \hat{v_e} = \hat{v}_{e\rightarrow f}$
- $\hat{v}_{e\rightarrow f}$ : смещенный вектор в исходных координатах
- $\hat{v_e}$ : исходный вектор


`Матрица перехода` от нового базиса к старому $A_{f\rightarrow e} = A_{e\rightarrow f}^{-1} $ -  матрица, в которой
- `столбцы`: координаты исходного базиса ($e$) выражаются через новые координаты ($f$)
при умножении которой на трансформированный координатный вектор в исходных координатах ( $\hat{v}_{e\rightarrow f}$ ),  
получается этот вектор в `новых` координатах:

$ \hat{v}_{f\rightarrow e} = A_{e\rightarrow f}^{-1} \cdot \hat{v}_{e\rightarrow f} $
- $\hat{v}_{e\rightarrow f}$ : вектор посе трансформации в исходных координитах

___
### _`ПРИМЕР`_

Для базисов:
- $e = (i, j)$,
    - $i = \begin  {pmatrix}
    1\\
    0\\
    \end{pmatrix}$, $j = \begin  {pmatrix}
    0\\
    1\\
    \end{pmatrix}$
    
- $f = (f_1, f_2)$,   
$f_1 = 2i + 2j$, $f_2 = -i + j$
    - $f_1 = \begin  {pmatrix}
    2\\
    2\\
    \end{pmatrix}$, $f_2 = \begin  {pmatrix}
    -1\\
    1\\
    \end{pmatrix}$

Матрицa перехода от базиса $e$ к базису $f$:

$A_{e\rightarrow f} = \begin  {pmatrix}
2 & -1 \\ 
2 & 1  \\
\end{pmatrix}$

Вектор `до` трансформации в исходных координатах:

$ \hat{v_e} = \begin  {pmatrix}
    0\\
    3\\
    \end{pmatrix}$

<img src='img/Ve.jpg' width=400>

___
Вектор `после` трансформации в `исходных` координатах:

- $\hat{v}_{e\rightarrow f} = A_{e\rightarrow f} \cdot \hat{v_e} $

- $ \hat{v}_{e\rightarrow f} = \begin  {pmatrix}
2 & -1 \\ 
2 & 1  \\
\end{pmatrix} \cdot \begin  {pmatrix}
    0\\
    -3\\
    \end{pmatrix}$
- $\hat{v}_{e\rightarrow f} = \begin  {pmatrix}
    3\\
    -3\\
    \end{pmatrix}$

<img src='img/Vf.jpg' width=400>

____
Вектор `после` трансформации в `новых` координатах:

- $ \hat{v}_{f\rightarrow e} = A_{e\rightarrow f}^{-1} \cdot \hat{v}_{e\rightarrow f}$

- $ \hat{v}_{f\rightarrow e} = \begin  {pmatrix}
2 & -1 \\ 
2 & 1  \\
\end{pmatrix}^{-1} \cdot \begin  {pmatrix}
    3\\
    -3\\
    \end{pmatrix} $ 

- $ \hat{v}_{f\rightarrow e} = \begin  {pmatrix}
    0\\
    -3\\
    \end{pmatrix}$

<img src='img/Vfe.jpg' width=400>


In [9]:
A_ef = np.array(((2,-1), (2,1)))
v_e = np.array(((3),(-3)))
v_f = np.linalg.inv(A_ef) @ v_e
print(f'Вектор в новых координатах: {v_f}')

v_e = A_ef @ v_f
print(f'Вектор в исходных координатах: {v_e}')


Вектор в новых координатах: [ 0. -3.]
Вектор в исходных координатах: [ 3. -3.]


____
## <a id=10>Изменение базисов в разных линейных пространствах</a>

Если:
- Для `нового` $ЛП^{n\times n}$ (_меньшей размерности_):
    - исходный базис $B$,
    - новый базис $\tilde{B}$ 
    - $S_{B\rightarrow \tilde{B}}$ : матрица перехода линейного отображения (столбцы - координаты нового базиса $\tilde{B}$ выражаются через исходные координаты $B$)
- Для `исходного` $ЛП^{m\times m}$ (_большей размерности_):
    - исходный базис $C$,
    - новый базис $\tilde{C}$ 
    - $T_{C\rightarrow \tilde{C}}$ : матрица перехода линейного отображения (столбцы - координаты нового базиса $\tilde{C}$ выражаются через исходные координаты $C$)
- $A_{C\rightarrow B}$: Матрица перехода от исходного базиса $C$ к новому $B$ (столбцы - координаты нового базиса $B$ выражаются через исходные координаты $C$)

То матрица перехода от нового базиса $\tilde{C}$ (_исходного ЛП_) к новому $\tilde{B}$ (_нового ЛП_):

$A_{\tilde{C}\rightarrow \tilde{B}} = T_{C\rightarrow \tilde{C}}^{-1} \cdot A_{C\rightarrow B} \cdot S_{B\rightarrow \tilde{B}}$ 


___
### _`ПРИМЕР`_

В `исходном` $ЛП^{4\times 4}$:
- $C = \begin  {pmatrix}
1 & 0 &0 &0 \\ 
0 & 1 &0 &0\\
0 & 0 &1 &0 \\
0 & 0 &0 &1 \\
\end{pmatrix}$
- $\tilde{C} = \begin  {pmatrix}
1 & 1 &0 &1 \\ 
1 & 0 &1 &0\\
0 & 1 &1 &0 \\
0 & 0 &0 &1 \\
\end{pmatrix} = T_{C\rightarrow \tilde{C}}$

В `новом` $ЛП^{3\times 3}$:
- $B = \begin  {pmatrix}
1 & 0 &0  \\ 
0 & 1 &0 \\
0 & 0 &1  \\
\end{pmatrix}$
- $\tilde{B} = \begin  {pmatrix}
1 & 0 &1  \\ 
1 & 1 &0 \\
0 & 1 &1 \\
\end{pmatrix} = S_{B\rightarrow \tilde{B}}$

`Матрица перехода` от исходного базиса $C$ к новому $B$:
- $A_{C\rightarrow B} = \begin  {pmatrix}
1 & 2 &0  \\ 
-1 & 1 &3 \\
3 & 7 &1 \\
-1 & 2 &4 \\
\end{pmatrix}$

Матрица перехода от нового базиса $\tilde{C}$ к новому $\tilde{B}$:

$A_{\tilde{C}\rightarrow \tilde{B}} = \begin  {pmatrix}
1 & 1 &0 &1 \\ 
1 & 0 &1 &0\\
0 & 1 &1 &0 \\
0 & 0 &0 &1 \\
\end{pmatrix}^{-1} \cdot \begin  {pmatrix}
1 & 2 &0  \\ 
-1 & 1 &3 \\
3 & 7 &1 \\
-1 & 2 &4 \\
\end{pmatrix} \cdot \begin  {pmatrix}
1 & 0 &1  \\ 
1 & 1 &0 \\
0 & 1 &1 \\
\end{pmatrix}$

$A_{\tilde{C}\rightarrow \tilde{B}} = \begin  {pmatrix}
-4 & -4 &-2  \\ 
6 & 0 &0 \\
4 & 8 &4 \\
1 & 6 &3 \\
\end{pmatrix}$

In [10]:
T = np.array(((1,1,0,1),(1,0,1,0),(0,1,1,0),(0,0,0,1)))
S = np.array(((1,0,1),(1,1,0),(0,1,1)))
A_old = np.array(((1,2,0),(-1,1,3),(3,7,1),(-1,2,4)))

A_new = np.linalg.inv(T) @ A_old @ S
print(A_new)

[[-4. -4. -2.]
 [ 6.  0.  0.]
 [ 4.  8.  4.]
 [ 1.  6.  3.]]


____
## <a id=11>Образ и ядро</a>
`Ядро (нулевое пространство)` линейного оператора  $L$ (_матрицы_) $ker(L)$ - множество всех векторов ($\hat{x}$) пространства $V$, при которых

$L \cdot \hat{x}= 0 $, где
- $0$ : принадлежит пространству $W$
- $\hat{x}$: векторное подпространство, пространства $V$
- $L: V \rightarrow W$, где
    - $V$ : векторное подпространство, пространства $W$


`Образ (пространство столбцов)` - векторное подпространство пространства $W$,  
 `достижимое` при линейном преобразовании `любого` вектора $V$

<img src='img/kernel.png' width=400>

___
### _`ПРИМЕР`_
При отображении $ЛП^{4\times 4}$ в $ЛП^{2\times 2}$:
- `Базовые векторы` $ЛП^{4\times 4}$: ($x_1, x_2, x_3, x_4$)
- `Матрица перехода`: $A = \begin  {pmatrix}
1 & 2 &-1 &0 \\ 
1 & 0 &0 &1\\
\end{pmatrix}$

`Базовые векторы` $ЛП^{2\times 2}$:

$\begin {pmatrix}
y_1\\
y_2\\
\end{pmatrix} = \begin {pmatrix}
1 & 2 &-1 &0 \\ 
1 & 0 &0 &1\\
\end{pmatrix} \cdot \begin{pmatrix}
x_1  \\ 
x_2 \\
x_3 \\
x_4 \\
\end{pmatrix}$

$\begin {pmatrix}
y_1\\
y_2\\
\end{pmatrix} = \begin {pmatrix}
x_1 +2x_2 - x_3\\
x_1 + x_4\\
\end{pmatrix}$

`Образ`:
- $Im(A) = span( \begin {pmatrix}
1\\
1\\ \end{pmatrix},\begin {pmatrix}
2\\
0\\ \end{pmatrix},\begin {pmatrix}
-1\\
0\\ \end{pmatrix},\begin {pmatrix}
0\\
1\\ \end{pmatrix} )$

`Ядро`:

$ker(A)$ - множество векторов $span(\hat{x})$, при которых:

- $A \cdot \hat{x}= 0 $

- $\begin {pmatrix}
1 & 2 &-1 &0 \\ 
1 & 0 &0 &1\\
\end{pmatrix} \rightarrow \begin {pmatrix}
1 & 0 &0 &1 \\ 
0 & 1 &-0.5 &-0.5\\
\end{pmatrix}$

- Матрица расширяется до `квадратной`, чтобы по диагонали были или `1` или `-1`:

    - $\begin {pmatrix}
1 & 0 &0 &1 \\ 
0 & 1 &-0.5 &-0.5\\
0 & 0 &-1 &0\\
0 & 0 &0 &-1\\
\end{pmatrix}$

- Решение уравнения $A \cdot x = 0$ - столбцы `содержащие -1`:

$ker(A) = span(\begin{pmatrix}
0  \\ 
-0.5 \\
-1 \\
0 \\
\end{pmatrix}, \begin{pmatrix}
1  \\ 
-0.5 \\
0 \\
-1 \\
\end{pmatrix})$

____
## <a id=12>Аффинное пространство</a>
`Аффинное пространство`(гиперплоскость) — это расширение векторного пространства, в которое включен дополнительный тип объектов — `точка`.   
В аффинном пространстве определена операция `сложения` точки и вектора, результатом которой является новая точка.   
Обратной ей является операция `вычитания` двух точек, результатом которой будет вектор.

`Линии`- одномерные афинные подпространства:

$y = x_0 + \lambda \cdot x_1$
- $x_0$ : точка поддержки (точка отсчета)
- $\lambda$ : параметр (число)
- $x_1$ : множество векторов, задающих направление

`Плоскости` - двумерные афинные подпространства:

$y = x_0 + \lambda_1 \cdot x_1 + \lambda_2 \cdot x_2$
- $x_0$ : точка поддержки (точка отсчета)
- $\lambda_1, \lambda_2$ : параметры(числа)
- $x_1, x_2$ : множество из двух линейно независимых векторов, охватывающих пространство направлений

____
## <a id=13>Норма векторного пространства</a>

`Норма` векторного пространства - функция, которая вектору $x$ присваивает значение длины $||x||$,  
соблюдается:
- $||\lambda \cdot x|| = |\lambda| \cdot ||x||$
- $||x + y|| \leq || x|| + ||y||$

`Метрика` - скалярное произведение разницы координат векторов

$d||x,y|| = ||x - y|| $

___
`Манхэттенская норма` (L1-норма) - Сумма всех модулей координат

$||d||_1 = \sum |x|$

<img src='img/l1-norm.jpg'>

In [11]:
v = np.array([5,-4])
np.linalg.norm(v, ord=1)

9.0

`Евклидова норма` (L2-норма) - Частный случай метрики Минковского для 2-х мерного пространства

 $ || d ||_2 = (\sqrt{\sum{x^2}}) $

<img src='img/l1.jpg'>


In [12]:
v = np.array([5,-4])
np.linalg.norm(v, ord=2)

6.4031242374328485

____
## <a id=13>Внутреннее произведение </a>

`Внутреннее произведение`$<x,y>$ - отображение пары векторов $x$ и $y$ на число

Обладает свойствами:
- `Билинейное` отображение $\Omega (x,y)$ - отображение пары векторов, в каждом векторе это отображение линейно:  
$\Omega (\lambda x+\gamma y, z) = \lambda \Omega(x,z) +  \gamma \Omega(y,z)$
- `Симметричное билинейное` отображение - если порядок следования векторов не важен:  
    $\Omega (x,y) = \Omega (y,x)$
- `Положительно определенное` - если,  
    $x \neq 0 : \Omega (x,x) > 0$  
    $x = 0 : \Omega (0,0) = 0$

`Скалярное` произведение  $(x,y)$ - частный случай внутренннего произведения:

$(x,y) = x^T \cdot y = \sum x_iy_i \rightarrow \lambda \in R$

___
### _`ПРИМЕР`_

`Внутреннее произведение` отличное от скалярного:

$<x,y> = x_1y_1 - (x_1y_2 + x_2y_1) + 2x_2y_2$

In [13]:
x = np.array((1,2))
y = np.array((3,4))
print(f'{x}, {y} -> {x @ y}')


[1 2], [3 4] -> 11


____
## <a id=14>Симметричные, положительно определенные матрицы</a>

`Симметричная, положительно определенная матрица` - симметричная матрица $A$, для которой

при $x \neq 0$ : 
- $x^T \cdot A \cdot x > 0$

`Симметричная, положительно полуопределенная матрица` - симметричная матрица $A$, для которой

при $x \neq 0$ :
-  $x^T \cdot A \cdot x \geq 0$

Симметричная, положительно определенная матрица $(A)$ определяет внутреннее произведение относительно упорядоченного базиса

$<x,y> = x^T \cdot A \cdot y$
- $x$ и $y$ : координатные представления относительно базиса

Всегда можно получить `симметричную положительную полуопределенную матрицу` из $A^{m \times n}$:

$S = A^T \cdot A$:
- $S$ : симметричная положительно `полуопределенная` матрица, если $rk(A)=n$, то симметричная положительно `определенная` матрица




In [14]:
A = np.array(((1,-0.8),(0,1),(1,0)))
S = A.T @ A
print(f'Из матрицы: \n {A} \n Симметричная положительно определенная матрица: \n {S}')

Из матрицы: 
 [[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]] 
 Симметричная положительно определенная матрица: 
 [[ 2.   -0.8 ]
 [-0.8   1.64]]


___

Симметричная матрица является `положительно определенной`, если:
- $ker(A) = 0$

Если $ker(A) \neq 0$, то

при некоторых $x$ принадлежащих $ker(A)$ : 

$A\cdot x = 0 \rightarrow x^T \cdot A \cdot x = 0$

- Диагональные элементы $A$ - `положительны`

___
### _`ПРИМЕР`_

`Симметричная, положительно определенная матрица`:

$A_1  = \begin {pmatrix}
9 & 6\\
6 & 5\\
\end{pmatrix} $, т.к

$x^T \cdot A \cdot x = (x_1 \ x_2) \cdot \begin {pmatrix} 
9 & 6\\
6 & 5\\
\end{pmatrix} \cdot \begin {pmatrix}
x_1 \\
x_2 \\
\end{pmatrix}= 9x_1^2 + 12x_1x_2 + 5x_2^2 = (3x_1 + 2x_2)^2 + x_2^2$

При любых $x \neq 0$ : 

$(3x_1 + 2x_2)^2 + x_2^2 > 0$


`Просто симметричная матрица`:

$A_1  = \begin {pmatrix}
9 & 6\\
6 & 3\\
\end{pmatrix} $

$x^T \cdot A \cdot x = (x_1 \ x_2) \cdot \begin {pmatrix}
9 & 6\\
6 & 3\\
\end{pmatrix} \cdot \begin {pmatrix}
x_1 \\
x_2 \\
\end{pmatrix}= 9x_1^2 + 12x_1x_2 + 3x_2^2 = (3x_1 + 2x_2)^2 - x_2^2 $

При некоторых $x$:

$(3x_1 + 2x_2)^2 - x_2^2 $ :  может быть $< 0$

____
## <a id=15>Углы и ортогональность</a>

`Угол` между векторами $x$ и $y$:

- $cos \omega = \frac{(x, y)}{||x|| * ||y||}$
- $\omega = arccos(cos \omega)$

In [15]:
x = np.array((1,1))
y = np.array((1,2))

cos_w = (x @ y) / ( np.linalg.norm(x) * np.linalg.norm(y) )
print(f'Угол между {x} и {y}: {np.arccos(cos_w):.2f} радиана, {np.rad2deg(np.arccos(cos_w)):.2f} градуса')


Угол между [1 1] и [1 2]: 0.32 радиана, 18.43 градуса


`Ортогональность` векторов ($x\perp y$):

- $(x, y)=x^T \cdot y = 0$,   
т.к. $cos \omega = 0$, при $\omega = 90^o$

`Ортонормированные векторы` $x$ и $y$ - векторы у которых:
- $(x, y) = 0$, перпендикулярны
- $||x|| = 1$
- $||y|| = 1$

In [16]:
x = np.array((1,0))
y = np.array((0,1))

cos_w = (x @ y) / ( np.linalg.norm(x) * np.linalg.norm(y) )
print(f'Угол между {x} и {y}: {np.arccos(cos_w):.2f} радиана, {np.rad2deg(np.arccos(cos_w)):.2f} градусов')

Угол между [1 0] и [0 1]: 1.57 радиана, 90.00 градусов


`Ортогональныая матрица` A - квадратная матрица, у которой:

- $A \cdot A^T = I = A^T \cdot A$, т.е.
    - $ A^T = A^{-1} $

Ортогональная матрица в качестве `линенйого оператора`:
- не меняет длину вектора:

    - $||A\cdot x||^2 = (A\cdot x)^T \cdot A \cdot x = x^T \cdot A^T \cdot A \cdot x = x^T \cdot I \cdot x = x^T \cdot x = ||x||^2$
- не меняет угол между векторами:

    - $cos \omega = \frac{(A\cdot x)^T \cdot A \cdot y}{||A\cdot x|| * ||A\cdot y||} = \frac{x^T\cdot A^T \cdot A \cdot y}{\sqrt{(x^T\cdot A^T \cdot A\cdot x )*( y^T\cdot A^T \cdot A\cdot y) }} = \frac{x^T\cdot I \cdot y}{\sqrt{(x^T\cdot I\cdot x )*( y^T\cdot I\cdot y) }} = \frac{x^T\cdot y}{\sqrt{(x^T\cdot x )*( y^T\cdot y) }} = \frac{(x,y)}{||x|| * ||y||}$

In [17]:
A = np.array(((0.707,0.707), (0.707,-0.707)))
x = np.array((1,1))
y = np.array((1,2))

cos_w = (x @ y) / ( np.linalg.norm(x) * np.linalg.norm(y) )
print(f'Угол между исходными {x} и {y} : {np.arccos(cos_w):.2f} радиана, {np.rad2deg(np.arccos(cos_w)):.2f} градуса')
print(f'Длина исходного вектора {x} : {np.linalg.norm(x):.2f}')
print(f'Длина исходного вектора {y} : {np.linalg.norm(y):.2f}')

print('Применяем линейный оператор:',A, sep='\n')
cos_w = (A @ x @ A @ y) / ( np.linalg.norm(A@x) * np.linalg.norm(A@y) )
print(f'Угол между {A @ x} и {A @ y} после преобразования: {np.arccos(cos_w):.2f} радиана, {np.rad2deg(np.arccos(cos_w)):.2f} градуса')
print(f'Длина вектора {A @ x} после преобразования: {np.linalg.norm(A @ x):.2f}')
print(f'Длина вектора {A @ y} после преобразования: {np.linalg.norm(A @ y):.2f}')




Угол между исходными [1 1] и [1 2] : 0.32 радиана, 18.43 градуса
Длина исходного вектора [1 1] : 1.41
Длина исходного вектора [1 2] : 2.24
Применяем линейный оператор:
[[ 0.707  0.707]
 [ 0.707 -0.707]]
Угол между [1.414 0.   ] и [ 2.121 -0.707] после преобразования: 0.32 радиана, 18.43 градуса
Длина вектора [1.414 0.   ] после преобразования: 1.41
Длина вектора [ 2.121 -0.707] после преобразования: 2.24


`Ортонормированный базис`:
- Скалярное произведение базисных векторов равно нулю:

$(b_1,..., b_n) = 0$

- Длины каждого базисного вектора равны единице:

$||b_1|| = 1$ $\dots$  $||b_n|| = 1$
    


____
## <a id=16>Ортогональное дополнение</a>

Для линейного пространства $S$ с размерностью $t $ существует подпространство $C$ с размерностью $d $, тогда:

- `ортогональное дополнение` $C^{\perp}$  - подпространство линейного пространства $S$ :
    - с `размерностью` $(t - d)$
    - $C^{\perp}$  состоит только из  векторов $\perp$ линейному пространству $C$
- любой вектор $x$ из пространства $S$ можно описать как:
    - $x = \sum \lambda_d c_d + \sum \lambda_{(t-d)} c^{\perp}_{(t-d)}$
        - $c_d$: `базисный вектор` пространства $C$, соответствующими коэффициентами $\lambda_d$
        - $c^{\perp}_{(t-d)}$: `базисный вектор` пространства $C^{\perp}$, соответствующими коэффициентами $\lambda_{(t-d)}$

___
### _`ПРИМЕР`_

В прострастве $S$ с базисисными векторами $e_1, e_2, e_3$, $dim(S)=3$
- $U$: подпростраство пространства $S$, $dim(U)=2$
- $w$: подпростраство $S$, $dim(w)=dim(S) - dim(U) = 1$, которое
    - состоит из векторов $\perp U$

<img src='img/ort.jpg' width=400>

____
## <a id=17>Проекция на прямую</a>

Пусть:

- $b$ : базис одномерного пространства $U$ (прямой)
- $x$ : вектор пространства ($R^n$) с размерностью $n$
- $\pi_U(x)$ : вектор пространства $U$, найближайший к $x$:
    - $\pi_U(x) = \lambda b$, т.к.
        - $b$ - базис $U$, а $\pi_U(x) \in U$
    - $||x - \pi_U(x)|| \rightarrow min$, значит:
        - $||x - \pi_U(x)|| \perp U$
        - $||x - \pi_U(x)|| \perp b$ :
            - $(x - \pi_U(x), b) = 0$
        
<img src='img/proj.jpg' width=400>

`Координата` $\lambda$ относительно базиса $b$:
- Т.к. $(x - \pi_U(x), b) = 0$, то:
    - $(x - \lambda b, b) = 0$
- Из свойства [билинейности](#13) скалярного произведения :
    - $(x - \lambda b, b) = (x, b) - \lambda (b, b) = 0$
- Т.к. $(x, b) - \lambda (b, b)$:

     - #### $\lambda = \frac{(x, b)}{(b, b)} = \frac{b^T \cdot x}{|| b||^2} = \frac{b^T \cdot x}{ b^T \cdot b}$

`Координаты точки` $\pi_U(x)$:
- #### $\pi_U(x) = \lambda b = \frac{b^T \cdot x}{ b^T \cdot b} * b$

`Длина` $\pi_U(x)$:
- $|| \pi_U(x) || = ||\lambda b|| = |\lambda| * ||b||$
- $|| \pi_U(x) || = \frac{b^T \cdot x}{ b^T \cdot b} * ||b|| = |cos \omega| * ||x||*||b|| *\frac{||b||}{||b||^2} = |cos \omega| * ||x||$, т.к.

    - $b^T \cdot x = |cos \omega| * ||x||*||b||$, где
        - $\omega$ : угол между векторами $x$ и $b$

`Проекционная матрица` $P_\pi$ - матрица (линейное отображение), при умножении которой на вектор $x$ получается вектор проекции $\pi_U(x)$:  

$P_\pi \cdot x = \pi_U(x)$
- $\pi_U(x) = \lambda b = \frac{b^T \cdot x}{ b^T \cdot b} * b = b * \frac{b^T \cdot x}{ b^T \cdot b} = \frac{b \cdot b^T}{ b^T \cdot b} \cdot x$
- $P_\pi = \frac{b \cdot b^T}{ b^T \cdot b}$



In [35]:
b = np.array((1,2,2)).reshape(1,3)

x = np.array((1,1,1))

P = (b.T @ b) / (b @ b.T)
pi_x = P @ x
print(f'Проекционная матрица \n {P} \n на прямую с базисом {b}')
print(f'Проекция вектора \n {x} \n на прямую с базисом {b}: \n {pi_x}')


Проекционная матрица 
 [[0.11111111 0.22222222 0.22222222]
 [0.22222222 0.44444444 0.44444444]
 [0.22222222 0.44444444 0.44444444]] 
 на прямую с базисом [[1 2 2]]
Проекция вектора 
 [1 1 1] 
 на прямую с базисом [[1 2 2]]: 
 [0.55555556 1.11111111 1.11111111]


array([[1, 2, 2],
       [2, 4, 4],
       [2, 4, 4]])

____
## <a id=18>Проекция на подпространство</a>

Проекции позволяют решать системы уравнений вида $A \cdot x = B$ для которых нет `точного` решения!  
Определяя такое подпространство, охватываемое столбцами матрицы $A$, которое будет `наиболее близким` к вектору $b$.  
Т.е. находить наименьшие суммарные `проекционные ошибки` (разностные векторы от вектора $b$ до подпространства, $\perp$ этому подпространству), например   
методом наименьших квадратов (МНК).
___
Пусть:

- $x$ : вектор пространства ($R^n$) с размерностью $n$
- $B$ : базис ($b_1,...b_m$) пространства $U$ с размерностью меньшей $n$ ( $m$ )
- $\pi_U(x)$ : вектор пространства $U$, найближайший к $x$:
    - $\pi_U(x) =  B \cdot \lambda$, где  
     $\lambda = (\lambda_1,...\lambda_m)$ т.к.
        - $B$ - базис $U$, а $\pi_U(x) \in U$
    - $||x - \pi_U(x)|| \rightarrow min$, значит:
        - $||x - \pi_U(x)|| \perp U$
        - $||x - \pi_U(x)|| \perp B$ :
            - $( B, x - \pi_U(x)) = 0$

<img src='img/proj f.jpg' width=500>

`Координаты проекции`в пространстве $U^m$ относительно базиса ($B$) $\lambda$:
- Т.к. $( B, x - \pi_U(x)) = 0$ и $\pi_U(x) =  B \cdot \lambda$, то:
    - $(B, x -  B \cdot \lambda) = 0$
- $(B, x -  B \cdot \lambda) = B^T \cdot (x - B \cdot \lambda) = B^T \cdot x - B^T \cdot B \cdot \lambda = 0$
    - $B^T \cdot x = B^T \cdot B \cdot \lambda $
    - $(B^T \cdot B)^{-1}\cdot B^T \cdot x = (B^T \cdot B)^{-1}\cdot B^T \cdot B \cdot \lambda $
    - $(B^T \cdot B)^{-1}\cdot B^T \cdot x = I \cdot \lambda $
- #### $\lambda = (B^T \cdot B)^{-1}\cdot B^T \cdot x$

`Координаты проекции` $\pi_U(x)$ в пространстве $R^n$ и лежащие в пространстве $U^m$:

Т.к. $\pi_U(x) = B \cdot \lambda$:
- $\pi_U(x) = B \cdot (B^T \cdot B)^{-1}\cdot B^T \cdot x$

`Проекционная матрица` $P_{\pi}$ - линейный оператор, преобразующий любой вектор из простраства $R^n$ в проекцию на простраство $U^m$ :

Т.к. $P_{\pi} \cdot x = \pi_U (x)$ :
- $P_{\pi} \cdot x  = B \cdot (B^T \cdot B)^{-1}\cdot B^T \cdot x$
- $P_{\pi} = B \cdot (B^T \cdot B)^{-1}\cdot B^T $

`Проекционная ошибка` - длина вектора $x - \pi_U(x)$:

$||x - \pi_U(x)||$

In [19]:
B = np.array(((1,0),(1,1), (1,2)))
x = np.array((6,0,0))

lmbda = np.linalg.inv(B.T @ B) @ B.T @ x
print(f'Координаты проекции относительно базиса \n {B}: \n {lmbda}')

pi_x = B @ lmbda
print(f'Проекция от вектора {x} относительно пространства U : \n {pi_x}')

proj_error = np.linalg.norm(x - pi_x) 
print(f'Проекционная ошибка: \n {proj_error:.2f}')

P = B @ np.linalg.inv(B.T @ B) @ B.T
print(f'Проекционная матрица : \n {P}')


Координаты проекции относительно базиса 
 [[1 0]
 [1 1]
 [1 2]]: 
 [ 5. -3.]
Проекция от вектора [6 0 0] относительно пространства U : 
 [ 5.  2. -1.]
Проекционная ошибка: 
 2.45
Проекционная матрица : 
 [[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


____
## <a id=19>Ортогонализация Грама-Шмидта</a>

`Ортогонализация Грама-Шмидта` - алгоритм создания ортогонального базиса ($u_1, ... u_n$) из любого (неортогонального) базиса ($b_1, ... b_n$):

Векторы $b_1$ и $b_1$ неортогональны

<img src='img/gama1.jpg' width=300>

1) $u_1 = b_1$

<img src='img/gama2.jpg' width=300>

2) $u_k = b_k - \pi_U(b_1) - ... - \pi_U(b_{k-1})$, где
    - $\pi_U(b_{1}) = \frac{u_{1} \cdot u_{1}^T}{||u_{1}||^2} \cdot b_{1}$

<img src='img/gama3.jpg' width=300>

3. Ортонормированный базис ($||e_k|| = 1$):

#### $e_k = \frac{u_k}{||u_k||}$


In [20]:
b_1 = np.array((2,0)).reshape(1,2)
b_2 = np.array((1,1)).reshape(1,2)

u_1 = b_1

u_2 = b_2.T - (u_1.T @ u_1) / (u_1 @ u_1.T) @ b_2.T
print(f'Ортогональный базис:\n {np.hstack((u_1.T, u_2))}')

e_1 = u_1.T / np.linalg.norm(u_1.T)
e_2 = u_2 / np.linalg.norm(u_2)
print(f'Ортонормированный базис:\n {np.hstack((e_1, e_2))}')

Ортогональный базис:
 [[2. 0.]
 [0. 1.]]
Ортонормированный базис:
 [[1. 0.]
 [0. 1.]]


____
## <a id=20>Проекция на афинное пространство</a>

Афинное пространство $L = x_0 + U$, где
- $U$: линейное пространство с базисными векторами  $b_1$ и $b_2$
- $x_0$: точка поддержки

<img src='img/aff_1.jpg' width=300>

Чтобы перейти к пространству $U$ нужно вычесть начальную точку $x_0$:
- $U = L - x_0$
- Определяется [проекция на подпространство](#17) $U$:
    - $\pi_U(x-x_0)$

<img src='img/aff_2.jpg' width=300>

Чтобы определить ортогональную проекцию на афинное пространство $L$:
- $\pi_L(x) = x_0 + \pi_U(x-x_0)$

<img src='img/aff_3.jpg' width=300>



____
## <a id=21>Поворот системы координат</a>

`Матрица поворота` $R(\Theta)$:
- $R(\Theta)^{2 \times 2} = \begin {pmatrix}
cos \Theta &- sin \Theta\\
 sin \Theta & cos \Theta\\
\end{pmatrix}$

<img src='img/pivot2.jpg' width=500>

- $R(\Theta)^{3 \times 3}$:
    - Поворот по оси $e_1$:

    $R(\Theta)_1 = \begin {pmatrix}
1 & 0 & 0\\
0 & cos \Theta &- sin \Theta\\
0 & sin \Theta & cos \Theta\\
\end{pmatrix}$

    - Поворот по оси $e_2$:

    $R(\Theta)_2 = \begin {pmatrix}
cos \Theta & 0 & - sin \Theta\\
0 & 1 & 0\\
sin \Theta & 0 & cos \Theta\\
\end{pmatrix}$

    - Поворот по оси $e_3$:

    $R(\Theta)_3 = \begin {pmatrix}
cos \Theta & - sin \Theta & 0\\
sin \Theta & cos \Theta & 0\\
0 & 0 & 1\\
\end{pmatrix}$

<img src='img/pivot3.jpg' width=400>


____
## <a id=22>Детерминант</a>

`Детерминант` квадратной матрицы $A$ - функция, отображающая матрицу $A$ в число

Нахождение детерминанта: `Разложение Лапласа`:

`По столбцу`

$det(A) = \sum (-1)^{k+j} * a_{kj} * det(A_{kj})$, где
- $k$ : текущая `строка`
- $j$ : `столбец` по которому производится разложение
- $det(A_{kj})$ : подматрица матрицы $A$, полученная путем удаления строки $k$ и стоолбца $j$ (`минор`)
___
`Свойства детерминанта`:
- $det(A) = V $: детерминант равен `объему фигуры`, образованной векторами (для $R^{2 \times 2}$ площади)
- В `треугольной` матрице детерминант равен произведению `диагональных` элементов
- $det(A^{n \times n}) \neq 0$, только когда:
    - $rk(A^{n \times n}) = n$ ($rk$ - [ранг](#8))

[Свойство матриц](#3)

- $det(A\cdot B) = det(A) * det(B)$
- $det(A^T) = det(A) $
- $det(A^{-1}) = \frac{1}{det(A)} $
- У [подобных](#10) матриц детерминанты равны:
    - $A$ подобна $\tilde{A}$, если существует $S$:
        - $\tilde{A} = S^{-1} \cdot A \cdot S$
        
[Элементарные преобразования](#5)

- Если `прибавить` к строке\столбцу другую строку\столбец, то детерминант `не изменится`
- Если `умножить` строку\столбец на число, то детерминант `умножается` на число
- Перестановка двух строк\столбцов `меняет` знак детерминанта




In [21]:
A = np.array(((2,6,1), (0,1,4), (-8,0,-1)))

det_A = np.linalg.det(A)
print(f'Детерминант матрицы \n {A}: \n {det_A:.0f}')

Детерминант матрицы 
 [[ 2  6  1]
 [ 0  1  4]
 [-8  0 -1]]: 
 -186


____
## <a id=23>След матрицы</a>

`След матрицы` $tr(A)$ - сумма диагональных элементов матрицы $A^{n \times n}$

`Свойства следа`:
- $tr(A+B) = tr(A) + tr(B)$
- $tr(\alpha A) = \alpha * tr(A)$
- $tr(A\cdot B) = tr(B\cdot A)$
- У [подобных](#10) матриц следы равны:
    - $tr(A) = tr(S^{-1} \cdot \tilde{A} \cdot S) = tr( S^{-1} \cdot S \cdot \tilde{A}) = tr(\tilde{A})$

In [22]:
A = np.array(((2,6,1), (0,1,4), (-8,0,-1)))
tr_A = np.trace(A)
print(f'След матрицы \n {A} \n -> {tr_A}')

След матрицы 
 [[ 2  6  1]
 [ 0  1  4]
 [-8  0 -1]] 
 -> 2


____
## <a id=24>Собственные значения и собственные векторы</a>

`Собственное значение` ($\lambda$) и `собственный вектор` ($x$) матрицы $A$:

$A \cdot x = \lambda \cdot x$
- $x$ : вектор, который не меняет направление после применения линейного оператора $A$
- $\lambda$ : число во сколько раз увеличился  ( уменьшился ) вектор после преобразования

$A \cdot x = \lambda \cdot x \rightarrow$

- $(A - I\cdot \lambda)\cdot x = 0$
- $det(A - I\cdot \lambda) = 0$

<img src='img/eigen.png' width=500>

_<a>Синий вектор</a> - собственный вектор линейного опрератора, который перекосил изображение,_  
_в данном случае собственное значение - 1, т.к. изображение не растянулось (не сузилось) вширь_

`Сонаправленные векторы` - векторы, указывающие в одном направлении

`Коллинеарные векторы` - векторы, указывающие в одном  направлении или `обратном` направлении

- Все векторы, коллинеарные собственному вектору, так же являются собственными векторами

`Характеристический многочлен` $p_A(\lambda)$:
- $ p_A(\lambda) = det(A - I\cdot \lambda) = det(A) + (-1)^{1-1} * tr(A) + (-1)^{2-1} * tr(A)+...+(-1)^{n-1} * tr(A)   $

`Алгебраическая кратность` $\lambda _i$ - количество вхождений корня $\lambda _i$ в характеристический многочлен

`Геометрическая кратность` $\lambda _i$ - количество линейно независимыхсобственных векторов, связанных с $\lambda_i$

`Собственное подпространство` $E_\lambda$ - подпространство пространства $R^{n \times n}$, которое охватывает множество всех собственных векторов, `связанных` с собственным значением $\lambda$.
- $E_\lambda$ : пространство решений СЛАУ:
    - $(A - I\cdot \lambda) \cdot x = 0$

`Собственный спектр` - набор всех собственных значений матрицы $A$
____
`Свойства собственных значений и собственных векторов`:
- $A$ и $A^T$ :
    - имеют `одинаковые` собственные значения
    - могут иметь `неодинаковые` собственные векторы
- $E_\lambda$ - нулевое пространство $A - I\cdot \lambda$, т.к.
    - $(A - I\cdot \lambda) \cdot x = 0$
- У [подобных](#10) матриц собственные значения равны
- [Симметричные положительно определенные матрицы](#14) всегда имеют $\lambda > 0$
- `Произведение` собственных значений матрицы $A$ - [детерминант](#22):

$\prod \lambda_i = det(A)$
- `Сумма` собственных значений матрицы $A$ - [след](#23):

$\sum \lambda_i = tr(A)$


___
### _`ПРИМЕР`_
`Детерминант`, `собственные векторы`, `собственные значения` различных линейных отображений

|Изображение| Матрица преобразования|Собственные векторы| площадь|
|:---:|:---:|:---:|:---:|
|<img src='img/eigen_ex1.jpg' width=500></img> | $A_1 = \begin {pmatrix}0.5 &0\\0 & 2 \\\end{pmatrix}$ | Вертикальная ось растягивается в 2 раза, горизонтальная сжимается в 2 раза. |Сохраняется|
|<img src='img/eigen_ex2.jpg' width=500></img> | $A_1 = \begin {pmatrix}1 &0.5\\0 & 1 \\\end{pmatrix}$ | Горизонтальная ось сохраняется |Сохраняется|
|<img src='img/eigen_ex3.jpg' width=500></img> | $A_1 = \begin {pmatrix}cos(\frac{\pi}{6}) &-sin(\frac{\pi}{6})\\sin(\frac{\pi}{6}) & cos(\frac{\pi}{6}) \\\end{pmatrix}$ | Не имеет растяжений |Сохраняется|
|<img src='img/eigen_ex4.jpg' width=500></img> | $A_1 = \begin {pmatrix}1 &-1\\-1 & 1 \\\end{pmatrix}$ | Связанный с $\lambda_2$ растягивается в 2 раза |Равна 0|
|<img src='img/eigen_ex5.jpg' width=500></img> | $A_1 = \begin {pmatrix}1 &0.5\\0.5 & 1 \\\end{pmatrix}$ | Связанный с $\lambda_1$ сжимается в 1.5 раза. Связанный с $\lambda_2$ растягивается в 2 раза  |Сжимается в 0.75 раз|





___
### _`ПРИМЕР`_

`Собственные значения и собственные векторы` матрицы $A = \begin {pmatrix}
4&2\\
 1 & 3\\
\end{pmatrix}$

- Находим `корни характеристического многочлена`:
    - $det(A - I \cdot \lambda) = 0$

    - $det(A - I \cdot \lambda) = det(\begin {pmatrix}
4&2\\
 1 & 3\\
\end{pmatrix} - \begin {pmatrix}
\lambda&0\\
0 & \lambda\\
\end{pmatrix}) = 0$

    - $det(\begin {pmatrix}
4&2\\
 1 & 3\\
\end{pmatrix} - \begin {pmatrix}
\lambda&0\\
0 & \lambda\\
\end{pmatrix}) =\begin {vmatrix}
4-\lambda &2\\
 1 & 3-\lambda \\
\end{vmatrix} = 0$

    - $\begin {vmatrix}
4-\lambda &2\\
 1 & 3-\lambda \\
\end{vmatrix} = (4 - \lambda) * (3 - \lambda) - 2 = 0$
    - $(4 - \lambda) * (3 - \lambda) - 2 = 10 - 7\lambda + \lambda^2 = (2-\lambda)*(5-\lambda) = 0$
    - $\lambda_1 = 5$, $\lambda_2 = 2$

- Находим `собственные векторы`:
    - $\begin {vmatrix}
4-\lambda &2\\
 1 & 3-\lambda \\
\end{vmatrix} \cdot x = 0$
    - `При` $\lambda = 5$:
        - $\begin {vmatrix}
4-5 &2\\
 1 & 3-5 \\
\end{vmatrix} \cdot \begin {pmatrix}
x_1\\
 x_2\\
\end{pmatrix} = \begin {vmatrix}
-1 &2\\
 1 & -2 \\
\end{vmatrix} \cdot \begin {pmatrix}
x_1\\
 x_2\\
\end{pmatrix} = 0$
        - $E_5 = span(\begin {pmatrix}
2\\
1\\
\end{pmatrix})$
    - `При` $\lambda = 2$:
        - $\begin {vmatrix}
4-2 &2\\
 1 & 3-2 \\
\end{vmatrix} \cdot \begin {pmatrix}
x_1\\
 x_2\\
\end{pmatrix} = \begin {vmatrix}
2 &2\\
 1 & 1 \\
\end{vmatrix} \cdot \begin {pmatrix}
x_1\\
 x_2\\
\end{pmatrix} = 0$
        - $E_2 = span(\begin {pmatrix}
1\\
-1\\
\end{pmatrix})$

In [23]:
A = np.array(((4,2), (1,3)))

eigen_vals, eigen_vectors = np.linalg.eig(A)
print(f'Собственные значения матрицы \n {A} \n -> {eigen_vals}')
print(f'Собственные векторы (нормированные) \n -> {eigen_vectors[:,0]} и {eigen_vectors[:,1]}')


Собственные значения матрицы 
 [[4 2]
 [1 3]] 
 -> [5. 2.]
Собственные векторы (нормированные) 
 -> [0.89442719 0.4472136 ] и [-0.70710678  0.70710678]


___
`Дефектная` матрица $A^{n \times n}$- квадратная матрица, у которой кол-во собственных векторов < $n$ (т.е. чтобы собственные векторы составляли базис $R^n$)

Всегда можно получить [симметричную положительную полуопределенную матрицу](#14) из $A^{m \times n}$:

$S = A^T \cdot A$:
- $S$ : симметричная положительно `полуопределенная` матрица, если $rk(A)=n$, то симметричная положительно `определенная` матрица

$S = A^T \cdot A = A^T \cdot (A^T)^T = (A^T \cdot A)^T = S^T \rightarrow$

$ S = S^T$
___
Для любой симмметричной матрицы $A^{n \times n}$ существует `диагональная матрица` с собственными значениями в `диагонали`:

$D = P^T \cdot A \cdot P$, где
- $P$ : матрица, у которой столбцы - `ортонормированные` собственные векторы
- $A$ : симметричная матрица

In [24]:
A = np.array(((3,2,2), (2,3,2), (2,2,3)))

eigen_values, eigen_vectors = np.linalg.eig(A)
D = np.round(eigen_vectors.T @ A @ eigen_vectors,0)
print(f'У симметричной матрицы \n {A} \n собственные значения:\n {eigen_values} \n ортонормированные собственные векторы: \n {eigen_vectors} \n диагональная матрица с собственными значениями: \n {D}')


У симметричной матрицы 
 [[3 2 2]
 [2 3 2]
 [2 2 3]] 
 собственные значения:
 [1. 7. 1.] 
 ортонормированные собственные векторы: 
 [[-0.81649658  0.57735027 -0.27546855]
 [ 0.40824829  0.57735027 -0.52791413]
 [ 0.40824829  0.57735027  0.80338269]] 
 диагональная матрица с собственными значениями: 
 [[1. 0. 0.]
 [0. 7. 0.]
 [0. 0. 1.]]


____
## <a id=25>Разложение Холецкого</a>

Разложение Холецкого - операция над [симметричными положительно определенными матрицами](#14), эквивалентная квадратному корню:

$A = L^T\cdot L$, где:
- $A$ : симметричная положительно определенная матрица
- $L$ : нижнетреугольная матрица с диагональными элементами > 0 ( _фактор Холецкого_ )




___
### _`ПРИМЕР`_

$A$ - симметричная положительно определенная матрица

<img src='img/cholesky1.jpg' width=500>

- Умножение $L^T\cdot L$ даёт:

<img src='img/cholesky2.jpg' width=350>

- `Диагональные элементы` матрицы $L$ :

<img src='img/cholesky3.jpg' width=400>

- Элементы `ниже диагонали` :

<img src='img/cholesky4.jpg' width=350>




In [25]:
A = np.array(((3,2,2), (2,3,2), (2,2,3)))

L = np.linalg.cholesky(A)
print(f'Для симметричной матрицы: \n {A} \n фактор Холецкого: \n {L}')

Для симметричной матрицы: 
 [[3 2 2]
 [2 3 2]
 [2 2 3]] 
 фактор Холецкого: 
 [[1.73205081 0.         0.        ]
 [1.15470054 1.29099445 0.        ]
 [1.15470054 0.51639778 1.18321596]]


____
## <a id=26>Собственное разложение и диагонализация</a>

Матрицу $A$ можно привести к диагональному виду $D$, если она [подобна](#10)  диагональной матрице $D$ (существует обратимая матрица $P$):

$D = P^{-1}\cdot A \cdot P$ 

`Собственное разложение`:

Квадратную ( [не дефектную](#24)) матрицу $A^{n \times n}$ можно разложить на:

$ A = P \cdot D \cdot P^{-1}$, где
- $P^{n \times n}$ : обратимая квадратная матрица, у которой столбцы - `ортонормированные` собственные векторы
- $D$ : диагональная матрица, диагональные элементы которое - собственные значения матрицы $A$


___
### _`ПРИМЕР`_

`Собственное разложение матрицы`

|Исходное изображение|Матрица как линейный оператор|Изображение после преобразования | Описание|
|:---:|:---:|:---:|:---:|
| <img src='img/proper1.jpg' width=150></img> | $A$ | <img src='img/proper3.jpg' width=150></img> |Собственные векторы умножены на собственные значения и отображаются в стандартных координатах   |

Описание `этапов` cобственного разложения квадратной матрицы

|Исходное изображение|Матрица как линейный оператор|Изображение после преобразования | Описание|
|:---:|:---:|:---:|:---:|
| <img src='img/proper1.jpg' width=150></img> | $P^{-1}$ | <img src='img/proper2.jpg' width=150></img> | Переход к базису из собственных векторов  |
| <img src='img/proper2.jpg' width=150></img> | $D$ | <img src='img/proper4.jpg' width=150></img> | Умножение каждого собственного вектора на свое собственное значение, что задает трансформацию пространства  |
| <img src='img/proper4.jpg' width=150></img> | $P$ | <img src='img/proper3.jpg' width=150></img> | Обратный переход к стандартному базису оттрансформированного пространства, где собственные векторы умножены на собственные значения и отображаются в стандартных координатах   |


In [26]:
A = np.array(((3,2,2), (2,3,1), (2,2,3)))

eigen_values, eigen_vectors = np.linalg.eig(A)
D = np.diag(eigen_values)
P = eigen_vectors
P_inv = np.linalg.inv(P)
A_redecomposed = P @ D @ P_inv

print(f'У квадратной матрицы \n {A} \n собственные значения:\n {eigen_values} \n матрица с собственными векторами в столбцах: \n {eigen_vectors} \n диагональная матрица с собственными значениями: \n {D}')
print(f'Собранная матрица A = \n {A_redecomposed}')


У квадратной матрицы 
 [[3 2 2]
 [2 3 1]
 [2 2 3]] 
 собственные значения:
 [6.64575131 1.         1.35424869] 
 матрица с собственными векторами в столбцах: 
 [[-6.11175207e-01 -7.07106781e-01  4.33437856e-01]
 [-5.02921199e-01  7.07106781e-01 -7.90103316e-01]
 [-6.11175207e-01  2.35230188e-16  4.33437856e-01]] 
 диагональная матрица с собственными значениями: 
 [[6.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.35424869]]
Собранная матрица A = 
 [[3. 2. 2.]
 [2. 3. 1.]
 [2. 2. 3.]]


___
Для `любой` симмметричной матрицы $A^{n \times n}$ существует `диагональная матрица` с собственными значениями в `диагонали`:

$D = P^T \cdot A \cdot P$, где
- $P$ : матрица, у которой столбцы - `ортонормированные` собственные векторы
- $A$ : симметричная матрица

In [27]:
A = np.array(((3,2,2), (2,3,2), (2,2,3)))

eigen_values, eigen_vectors = np.linalg.eig(A)
D = np.round(eigen_vectors.T @ A @ eigen_vectors,0)
print(f'У симметричной матрицы \n {A} \n собственные значения:\n {eigen_values} \n ортонормированные собственные векторы: \n {eigen_vectors} \n диагональная матрица с собственными значениями: \n {D}')

У симметричной матрицы 
 [[3 2 2]
 [2 3 2]
 [2 2 3]] 
 собственные значения:
 [1. 7. 1.] 
 ортонормированные собственные векторы: 
 [[-0.81649658  0.57735027 -0.27546855]
 [ 0.40824829  0.57735027 -0.52791413]
 [ 0.40824829  0.57735027  0.80338269]] 
 диагональная матрица с собственными значениями: 
 [[1. 0. 0.]
 [0. 7. 0.]
 [0. 0. 1.]]


____
## <a id=27>Сингулярное разложение (SVD разложение)</a>

Любую матрицу $A$ любой формы можно представить как:

$ A_{m \times n} = U_{m \times m} \cdot \Sigma_{m \times n} \cdot V_{n \times n}^T$, где:
- $ U_{m \times m}$ : ортогональная матрица, состоящая из левосингулярных векторов
- $ V_{n \times n}$ : ортогональная матрица, состоящая из правосингулярных векторов
- $\Sigma_{m \times n}$ : диагональная матрица с сингулярными значениями $\sigma_i$ по диагонали (в порядке убывания)
    - все недиагональные элементы заполнены нулями


___
### _`ПРИМЕР`_

#### `Визуализация SVD-разложение матрицы` :

Для $A^{3 \times 2} = \begin {pmatrix}
1&-0.8\\
0 & 1\\
1 & 0\\
\end{pmatrix}$ 

существуют такие матрицы $U_{3 \times 3}, \Sigma_{3 \times 2} , V_{2 \times 2}^T$, что :

<img src='img/svd.jpg' width=400>

1.) `Матрица` $V^{T} = \begin {pmatrix}
-0.78 & 0.62\\
-0.62 & -0.78\\
\end{pmatrix}$ 

- Меняет стандартный базис на базис ($v_1, v_2$)
- $V^{T} = V^{-1} $ (т.к. ортогональна)

2.) `Матрица` $\Sigma = \begin {pmatrix}
1.62&0\\
0 & 1\\
0 & 0\\
\end{pmatrix}$ 

- Масштабирует новые координаты в базисе ($v_1, v_2$), умножением на сингулярные значения ($\sigma_1 v_1,\sigma_2 v_2$)
- Преобразует в третье измерение, добавляя третий базисный вектор отрогонально базису ($\sigma_1 v_1,\sigma_2 v_2$)
    - попрежнему все векторы лежат в базисе ($\sigma_1 v_1,\sigma_2 v_2$)

3.) `Матрица` $U = \begin {pmatrix}
-0.79&0 & -0.62\\
0.38 & -0.78 & -0.49\\
-0.48 & -0.62 & 0.62\\
\end{pmatrix}$ 

- Меняет базис на стандартный базис в трех измерениях поворотом в трехмерном линейном пространстве

In [28]:
A = np.array(((1,-0.8),(0,1),(1,0)))
U, E, V = np.linalg.svd(A)

Ediag = np.vstack((np.diag(E), np.array(((0),(0)))))
EV = np.diag(E) @ V
EV_stacked = np.vstack((EV, np.array(((0),(0)))))

A_redecomposed = U @ EV_stacked

print(f'Для матрицы: \n {A} \n Матрица U:\n {np.round(U,2)} \n Матрица E:\n {np.round(Ediag,2)} \n Матрица V:\n {np.round(V,2)}')

Для матрицы: 
 [[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]] 
 Матрица U:
 [[-0.79  0.   -0.62]
 [ 0.38 -0.78 -0.49]
 [-0.48 -0.62  0.62]] 
 Матрица E:
 [[1.62 0.  ]
 [0.   1.  ]
 [0.   0.  ]] 
 Матрица V:
 [[-0.78  0.62]
 [-0.62 -0.78]]


____
## <a id=28>Взаимосвязь и отличния Собственного разложенеия и Сингулярного разложения </a>

`Отличия` между разложениями матриц:

| Свойство | [SVD-разложение](#26)|[Собственное разложение](#27) |
|:---|:---:|:---:|
| Формула разложения | $A = U \cdot \Sigma \cdot V^T$ | $A = P \cdot D \cdot P^{-1}$ |
| Алгоритм | Переход к базису $V^T$ $\rightarrow$ Масштабирование новых базисных векторов $\Sigma \cdot V^T$ $\rightarrow$  Переход к базису $U$ | Переход к базису $P^T$ $\rightarrow$ Масштабирование новых базисных векторов $D \cdot P^T$ $\rightarrow$  Возвращение к стандартному базису |
| Существует | Для `любых` матриц | Только для `квадратных` [не дефектных](#24) матриц |
| Векторы в матрицах разложения | В $U$, $V$ `ортонормированы` | В $P$ `не обязательно` ортонормированы  | 
| Размерность матриц разложения | Могут быть в `разных` размерностях | `Одинаковой` размерности | 
| Отношения между матрицами разложения | $U$ и $V$ Обычно разных размерностей | $P$ обратна $P^{-1}$ | 
| Элементы диагональной матрицы | $\sigma_i$ > 0 | $\lambda$ любые (в т.ч. комплексные) | 

`Взаимосвязь` между разложениями матриц:

- Если  матрица $A$ - `симметричная`, то SVD-разложение `аналогично` собственному разложению

|[SVD-разложение](#26) | [Собственное разложение](#27) |  
|---:|---|
| Векторы $U$ $\rightarrow$ | собственные векторы $A \cdot A^T$ |   
| Векторы $V$ $\rightarrow$ | собственные векторы $A^T \cdot A$ |
| $\sigma_i \neq 0$ матрицы $A$ $\rightarrow$| $\sqrt \lambda_i$ матрицы $A\cdot A^T$ и $A^T\cdot A$ |



___
### _`ПРИМЕР`_

#### `SVD`-разложение через `собственное` разложение матрицы:

$A = \begin {pmatrix}
1 & 0 & 1\\
-2 & 1 & 0\\
\end{pmatrix}$ 

In [29]:
A = np.array(((1,0,1), (-2,1,0)))
A

array([[ 1,  0,  1],
       [-2,  1,  0]])

___
1) $A^T \cdot A $ : `симметричная полуопределенная матрица`  
- для которой существует диагональная матрица $D$ с собственными значениями по диагонали

In [30]:
At_A = A.T @ A
At_A

array([[ 5, -2,  1],
       [-2,  1,  0],
       [ 1,  0,  1]])

___
2. `Собственное разложение` матрицы $A^T \cdot A $:
- $A^T \cdot A = P \cdot D \cdot P^T$:
    - $D$ : диагональна матрица с собственными значениями по диагонали
    - $P$ : квадратная матрица с правосингулярными векторами в столбцах
        - $P = V$
        
2.2. Квадратная матрица с `правосингулярными` векторами в столбцах $P$ :

In [31]:
eigvals, eigvecs = np.linalg.eig(At_A)
P = eigvecs
V = P

print(f'Матрица с правосингулярными векторами в столбцах: \n {np.round(V,2)}')


Матрица с правосингулярными векторами в столбцах: 
 [[ 0.91 -0.41  0.  ]
 [-0.37 -0.82  0.45]
 [ 0.18  0.41  0.89]]


___
2.3. `Левосингулярные` векторы:

$\sigma = \sqrt\lambda$ : сингулярные значения матрицы $A$ - корень из собственных значений, т.к.:
- $\lambda$ : собственные значения матрицы $A^T \cdot A$

$u_i =\frac{A \cdot v_i}{||A \cdot v_i||} =   = \frac{1}{\sqrt \lambda} * A \cdot v_i = \frac{1}{\sigma_i} * A \cdot v_i$

- $u_1 = \frac{1}{\sigma_1} * A \cdot v_1$

- $u_2 = \frac{1}{\sigma_2} * A \cdot v_2$




In [32]:
singular_vals = np.sqrt(eigvals,)
singular_vals = np.nan_to_num(singular_vals,0)
print(f'Правосингулярному вектору v1: {V.T[0]} \n соответсвует сингулярное значение: {np.round(singular_vals[0],2)}')
print(f'Правосингулярному вектору v2: {V.T[2]} \n соответсвует сингулярное значение: {np.round(singular_vals[2],2)}')

u_1 = (1/singular_vals[0]) * A @ V.T[0]
u_2 = (1/singular_vals[2]) * A @ V.T[2]
u_1 = u_1.reshape(2,1)
u_2 = u_2.reshape(2,1)

print(f'Левосингулярный вектор u1: {u_1}')
print(f'Левосингулярный вектор u2: {u_2}')
U = np.hstack((u_1, u_2))
print(f'Матрица с левосингулярными векторами в столбцах: \n {np.round(U,2)}')


Правосингулярному вектору v1: [ 0.91287093 -0.36514837  0.18257419] 
 соответсвует сингулярное значение: 2.45
Правосингулярному вектору v2: [1.56205192e-33 4.47213595e-01 8.94427191e-01] 
 соответсвует сингулярное значение: 1.0
Левосингулярный вектор u1: [[ 0.4472136 ]
 [-0.89442719]]
Левосингулярный вектор u2: [[0.89442719]
 [0.4472136 ]]
Матрица с левосингулярными векторами в столбцах: 
 [[ 0.45  0.89]
 [-0.89  0.45]]


C:\Users\nazar\AppData\Local\Temp\ipykernel_5480\2129740508.py:1: RuntimeWarning: invalid value encountered in sqrt
  singular_vals = np.sqrt(eigvals,)


3. $A = U \cdot \Sigma \cdot V^T$

In [33]:
E = np.diag(singular_vals)
E = np.vstack((E[0,0:], E[2,0:]))

A_redecomposed = U @ E @ V.T
np.round(A_redecomposed,2)

print(f'Для матрицы: \n {A} \n Матрица U:\n {np.round(U,2)} \n Матрица E:\n {np.round(E,2)} \n Матрица V:\n {np.round(V,2)}')

Для матрицы: 
 [[ 1  0  1]
 [-2  1  0]] 
 Матрица U:
 [[ 0.45  0.89]
 [-0.89  0.45]] 
 Матрица E:
 [[2.45 0.   0.  ]
 [0.   0.   1.  ]] 
 Матрица V:
 [[ 0.91 -0.41  0.  ]
 [-0.37 -0.82  0.45]
 [ 0.18  0.41  0.89]]


____
## <a id=29>Матричное приближение </a>

Матрица $A$ может быть записана как сумма матриц $A_i$,

- $A = \sum \sigma_i \cdot u_i \cdot v_i^T = \sum \sigma_i \cdot A_i$

    - $rk(A_i) = 1$

In [34]:
u1 = np.array((1,2,3)).reshape(3,1)
u2 = np.array((1,2,3)).reshape(3,1)

v1 = np.array((1,1)).reshape(2,1)
v2 = np.array((2,2)).reshape(2,1)

A1 = u1 @ v1.T
A2 = u2 @ v2.T

A = A1 + A2 
print(f'Скалярное умножение векторов\n {u1} и {v1.T} \n дает матрицу A1:\n {A1} ')
print(f'Сумма матриц A1 + A2 =\n {A}')


Скалярное умножение векторов
 [[1]
 [2]
 [3]] и [[1 1]] 
 дает матрицу A1:
 [[1 1]
 [2 2]
 [3 3]] 
Сумма матриц A1 + A2 =
 [[3 3]
 [6 6]
 [9 9]]


___
`Спектральная норма матрицы` - наибольшее сингулярное значение $\sigma_1$, определяет, насколько длинным может стать любой вектор при умножении на $A$:

#### $||A||_2 = max\frac{||A\cdot x||_2}{||x||_2}$

`Теорема Эккарта-Юнга`

Чтобы получить матрицу `меньшего ранга`, `наиболее близкую` (по спектральной норме) можно использовать `сингулярное разложение` матриц.

Для матриц $A^{m \times n}$ и $B^{m \times n}$:
- $rk(A) > rk(B)$

Спектральная норма разницы матриц $A^{m \times n}$ и $B^{m \times n}$ `минимальна`:

- $|| A - B||_2 \rightarrow min$, когда:
    - Матрица $B$ составлена из сингулярного разложения:
        - $B = U \cdot \Sigma_{rk(B)} \cdot V^T$, где
            - $\Sigma_{rk(B)}$ : все сингулярные значения заменены на 0, кроме $rk(B)$ наибольших

____
## <a id=30>Типы матриц </a>

<img src='img/Матрицы.jpg' width=1200></img>

___
___
## $\uArr$ [К содержанию](#cont)