# `Массивы` в библиотеке `numpy`
<img src='data/numpylogo.png'></img>
___



> ## <h3 id='comp' style='color:cyan'> Оглавление</h3>
- [Создание массивов](#create)
- [Случайные элементы](#random)
- [Срезы](#slice)
- [Операции](#oper)
  - [Линейная алгебра](#linalg)
  - [Статистические функции](#stat)
  - [Методы классических массивов](#classic)
- [Информация о массивах](#info)
- [Импорт/экспорт данных](#import)

   ___
   ***
   ## <h1 id='create' style='color:violet'> Создание массивов</h1>
   ---

numpy<span style='color:red'>**.array**</span> ( **iter** ) - _`Создает вектор`_ из итератора **iter**

In [1]:
import numpy as np

lst1 = [1,2,3]
tup2 = (4,5,6)

vector_1 = np.array(lst1)
vector_2 = np.array(tup2)
number = 5

print(f'Сложение векторов: {vector_1 + vector_2}')
print(f'Умножение векторов: {vector_1 * vector_2}')
print(f'Умножение вектора на число: {vector_1 * number}')


Сложение векторов: [5 7 9]
Умножение векторов: [ 4 10 18]
Умножение вектора на число: [ 5 10 15]


numpy<span style='color:red'>**.arange**</span> ( **n** ) - _`Создает вектор`_ из чисел от 0 до **n**

In [2]:
ar_range = np.arange(7)
print(ar_range)


[0 1 2 3 4 5 6]


numpy<span style='color:red'>**.linspace**</span> ( **start, finish, count** ) - _`Создает вектор`_ из чисел начиная от **start** до **finish**, количество интервалов **count**, параметр **retstep=True** возвращает шаг элементов

In [3]:
ar_lin, step = np.linspace(0, 10, 6, retstep=True)
print(ar_lin,'\n','Шаг: ', step)


[ 0.  2.  4.  6.  8. 10.] 
 Шаг:  2.0


numpy<span style='color:red'>**.empty**</span> ( **(n, m)** ) - _`Создает пустую матрицу`_ кол-во строк: **n**, столбцов **m**

In [4]:
matrix_empty = np.empty((2,4))
print(matrix_empty)


[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.31420855e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306]]


numpy<span style='color:red'>**.zeros**</span> ( **(n, m)** ) - _`Создает матрицу, заполненную '0'`_ кол-во строк: **n**, столбцов **m**

In [5]:
matrix_0 = np.zeros((3, 2))
print(matrix_0)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


numpy<span style='color:red'>**.eye**</span> **( n )**  - _`Создает единичную матрицу`_ размером: **n**

In [6]:
E = np.eye(3)
print(E)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy<span style='color:red'>**.diag**</span> **( iter )**  - _`Создает диагональную матрицу`_ из элементов объекта: **iter**

In [7]:
diagonal = np.diag(range(5))
print(diagonal)


[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


numpy<span style='color:red'>**.ones**</span> ( **(n, m)** ) - _`Создает матрицу, заполненную '1'`_ кол-во строк: **n**, столбцов **m**

In [8]:
matrix_1 = np.ones((2,3), int)
print(matrix_1)


[[1 1 1]
 [1 1 1]]


<span style='color:blue'>**.reshape**</span> **(n, m)** - Преобразует массив в _`матрицу`_  размером **n, m** , параметр **order='F'** заполняет элементы массива по столбцам, а не по строкам

In [9]:
arr = np.arange(12)
print(arr)

print('_'*40,end='\n'*2)

M = arr.reshape(3,4)
print(M)
M = arr.reshape(3,4, order='F')

print(M)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
________________________________________

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


<span style='color:blue'>**.sort**</span> **(arr)** - `Сортирует` массив 

In [10]:
arr = np.array([6,5,4,3,2])
sorted_arr = np.sort(arr)
print(arr)
print(sorted_arr)


[6 5 4 3 2]
[2 3 4 5 6]


numpy<span style='color:red'>**.concatenate**</span> ( **(arr1, arr2...)** ) - _`Объединяет` массивы 

In [11]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])


np.concatenate((arr_1, arr_2, arr_3))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

  ---
   ## <h1 id='random' style='color:violet'> Массивы со случайными элементами</h1>   
  ***


numpy<span style='color:red'>**.random.random**</span> ( **(n, m)** ) - _`Создает матрицу , заполненную случайными числами от 0 до 1`_ кол-во строк: **n**, столбцов **m**  (в кортеже)  
numpy<span style='color:red'>**.random.sample**</span> ( **(n, m)** ) - _`Создает матрицу , заполненную случайными числами от 0 до 1`_ кол-во строк: **n**, столбцов **m**  (в кортеже)  
numpy<span style='color:red'>**.random.rand**</span> ( **n, m** ) - _`Создает матрицу , заполненную случайными числами от 0 до 1`_ кол-во строк: **n**, столбцов **m**  
numpy<span style='color:red'>**.random.uniform**</span> ( **n, m**, **size=(r, c)** ) - _`Создает матрицу , заполненную случайными числами от n до m`_ кол-во строк: **r**, столбцов **c**

In [12]:
matrix_random = np.random.random((3, 4))
matrix_sample = np.random.sample((1,2))
matrix_rand = np.random.rand(2, 3)
matrix_uniform = np.random.uniform(-10,10, size=(2,3))

print(matrix_random,'\n')
print(matrix_sample,'\n')
print(matrix_rand,'\n')
print(matrix_uniform)


[[0.89645674 0.39565918 0.11054847 0.33304119]
 [0.3834722  0.16573525 0.4800862  0.07636575]
 [0.02888738 0.10825328 0.03700334 0.69259739]] 

[[0.25303716 0.6461204 ]] 

[[0.0675439  0.32397032 0.1762755 ]
 [0.4055417  0.36979734 0.31143472]] 

[[-0.03902049  4.71977533 -0.9372094 ]
 [ 2.42318089 -8.85903463 -0.20530997]]


numpy<span style='color:red'>**.random.randint**</span> **(k, l, size=(n, m)**  - _`Создает матрицу, заполненную случайными числами` от **k** до **l**_ , кол-во строк: **n**, столбцов **m**

In [13]:
M_rand = np.random.randint(3, 10, size=(3,3))
print(M_rand)


[[3 9 3]
 [5 5 3]
 [3 8 5]]


numpy<span style='color:blue'>**.random.shuffle**</span> **(arr)** - `Перемешивает` элементы массива (возращает None)  
numpy<span style='color:blue'>**.random.permutation**</span> **(arr)** - Возвращает `Перемешианные` элементы массива 

In [14]:
M = np.array([1, 2, 3, 4, 5])

new_arr = np.random.permutation(M)
print(new_arr)
np.random.shuffle(M)
print(M)


[1 2 3 4 5]
[5 1 2 3 4]


numpy<span style='color:blue'>**.random.choice**</span> **(arr, size= number, replace=False)** - Возвращает `массив` из `number`количества **случайных** элементов массива `arr`, при replace=False `без повторений` элементов

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
choice = np.random.choice(arr, size=3, replace=False)
print(f'Из массива {arr} выбраны 3 случайные значения:{choice}')


Из массива [1 2 3 4 5 6 7 8] выбраны 3 случайные значения:[5 4 6]


numpy<span style='color:red'>**.random.seed**</span> **(n)**  - Для **последующих** случайных объектов значения будут фиксированы( `не случайны` ), **n** - любое число >= 0

In [16]:
random_arr = np.random.rand(3)
print(f'Массив со случайными элементами: {random_arr}')


Массив со случайными элементами: [0.05923566 0.71166089 0.67622361]


In [17]:
np.random.seed(2)
print(f'Значения массива зафиксированны: {random_arr}')


Значения массива зафиксированны: [0.05923566 0.71166089 0.67622361]


  ---
   ## <h2 id='slice' style='color:violet'> Срезы массивов</h2>   
  ***

In [18]:
M = np.arange(12).reshape(3,4)
print(M,'_'*40,sep='\n')

arr_row = M[1:]
arr_col = M[:, 1:2]
arr_el = M[1,1]

arr_filt = M[(M>6) & (M<10)]

print(f'Срез ряда:\n {arr_row}')
print(f'Срез столбца:\n {arr_col}')
print(f'Срез элемента: {arr_el}')
print(f'Срез по условию 6 < M < 10: {arr_filt}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
________________________________________
Срез ряда:
 [[ 4  5  6  7]
 [ 8  9 10 11]]
Срез столбца:
 [[1]
 [5]
 [9]]
Срез элемента: 5
Срез по условию 6 < M < 10: [7 8 9]


  ---
   ## <h1 id='oper' style='color:violet'> Операции над массивами</h1>   
  ***

numpy<span style='color:red'>**.matmul**</span> ( **m1, m2** ) - _`Попарно умножает`_ матрицы **m1, m2**

In [19]:
A = np.array([-12,13])
B = np.array([[1,2],[-3,4]])
C = np.array([[1,2,3],[5,-2,0]])
D = np.array([-1,1,3])

AB = np.dot(A,B)
print(f'Результирующая матрица AB: {AB}')

CD = C @ D
print(f'Результирующая матрица CD: {CD}')

ABCD = np.matmul(AB,CD)
print(f'Результирующая матрица ABCD: {ABCD}')


Результирующая матрица AB: [-51  28]
Результирующая матрица CD: [10 -7]
Результирующая матрица ABCD: -706


numpy<span style='color:red'>**.transpose**</span> ( **matrix** ) - _`Транспонирует`_ матрицу **matrix**

In [20]:
nested_lst = [lst1, tup2]

matrix = np.array(nested_lst)
transposed_matrix = np.transpose(matrix)
print(f'Входящая матрица: \n{matrix}')
print(f'Транспонированная матрица: \n{transposed_matrix}')


Входящая матрица: 
[[1 2 3]
 [4 5 6]]
Транспонированная матрица: 
[[1 4]
 [2 5]
 [3 6]]


<span style='color:blue'>**.prod**</span> **( )** - _`Перемножает элементы`_ **объекта** numpy

In [21]:
lst = [n for m in range(1,4) for n in range(1,4)]

M = np.array(lst).reshape(3,3)
print(M)
print(M.prod())


[[1 2 3]
 [1 2 3]
 [1 2 3]]
216


numpy<span style='color:red'>**.cumsum**</span> ( **array** ) - _`Создает массив из элементов накопительной суммой`_ объекта numpy **array** 

In [22]:
arr = np.arange(5)[1:]

print(f'Исходный массив:\n {arr}\n')
print(f'Массив с накопительной суммой:\n {np.cumsum(arr)}')


Исходный массив:
 [1 2 3 4]

Массив с накопительной суммой:
 [ 1  3  6 10]


numpy<span style='color:red'>**.cumprod**</span> ( **array** ) - _`Создает массив из элементов накопительного произведения`_ объекта numpy **array** 

In [23]:
arr = np.arange(5)[1:]
print(arr)
print(np.cumprod(arr))


[1 2 3 4]
[ 1  2  6 24]


numpy<span style='color:red'>**.flip**</span> ( **array** ) - _`Переворачивает элементы`_ объекта numpy **array** 

In [24]:
arr = np.array(range(25)).reshape(5,5)
print(f'Исходный массив:\n {arr}\n')
print(f'Перевернутый массив:\n {np.flip(arr)}')


Исходный массив:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Перевернутый массив:
 [[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


numpy<span style='color:red'>**.corrcoef**</span> ( **X**, **Y** ) - _Возвращает матрицу `коэффициентов корреляции`_ для массивов **X** и **Y** 

In [25]:
X = np.arange(10)
Y = np.random.randint(0,10,size=(10))

print('X: ',X, '\n','Y: ', Y)
np.corrcoef(X, Y).round(2)


X:  [0 1 2 3 4 5 6 7 8 9] 
 Y:  [8 8 6 2 8 7 2 1 5 4]


array([[ 1.  , -0.56],
       [-0.56,  1.  ]])

___
## <h3 id='linalg' style='color:red'> Линейная алгебра</h3> 
___

numpy<span style='color:red'>**.linalg.norm**</span> ( **array** ) - _`Возвращает матричную норму(длину)`_ объекта numpy **array** 

In [26]:
M  = np.array(range(10)).reshape(2,5)

matrix_norm = np.linalg.norm(M)
print(f'Матричная норма: {matrix_norm}')


Матричная норма: 16.881943016134134


numpy<span style='color:red'>**.linalg.solve**</span> ( **A, B** ) - _`Возвращает вектор коэффициентов СЛАУ`_, матрица системы **A**, вектор ответов **B** 

In [27]:
A = np.array([[1,2,-3],[2,1,2],[3,-2,-1]])
B = np.array([4,3,9])
result = np.linalg.solve(A,B)
print(f'X = {result[0]}')
print(f'Y = {result[1]}')
print(f'Z = {result[2]}')


X = 2.475
Y = -0.39999999999999974
Z = -0.7749999999999999


___
numpy<span style='color:red'>**.linalg.inv**</span> ( **A** ) - _`Возвращает обратную матрицу`_, для исходной матрицы **A**
___

In [28]:
E = np.eye(4)*2

rev_M = np.linalg.inv(E)
print(f'Исходная матрица:\n {E}')
print(f'Обратная матрица:\n {rev_M}')


Исходная матрица:
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
Обратная матрица:
 [[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0.5]]


___
## <h3 id='stat' style='color:red'> Статистические функции</h3> 
___

numpy<span style='color:red'>**.std**</span> ( **array** ) - _`Возвращает стандартное отклонение`_ в объекте numpy **array** 

numpy<span style='color:red'>**.var**</span> ( **array** ) - _`Возвращает дисперсию`_ в объекте numpy **array** 

numpy<span style='color:red'>**.sum**</span> ( **array** ) - _`Возвращает сумму элементов`_ в объекте numpy **array** 

numpy<span style='color:red'>**.min**</span> ( **array** ) - _`Возвращает минимальное значение`_ в объекте numpy **array**  

numpy<span style='color:red'>**.max**</span> ( **array** ) - _`Возвращает максимальное значение`_ в объекте numpy **array**  

numpy<span style='color:red'>**.average**</span> ( **array** ) - _`Возвращает среднее значение`_ в объекте numpy **array**    

numpy<span style='color:red'>**.median**</span> ( **array** ) - _`Возвращает медиану`_ в объекте numpy **array**  

numpy<span style='color:red'>**.mean**</span> ( **array, axis= 0** ) - _`Возвращает среднее значение`_ в объекте numpy **array** _` в столбцах`_, **axis= 0** ( _` в строках`_, **axis= 1** )


In [29]:
M = np.arange(12).reshape(3,4)
print(M)
print('_'*40,end='\n'*2)
print(f'Минимальное значение:{np.amin(M)}')
print(f'Максимальное значение:{np.amax(M)}')
print(f'Среднее значение:{np.average(M)}')
print(f'Среднее значение в столбцах: {np.mean(M, axis=0)}')
print(f'Среднее значение в строках: {np.mean(M, axis=1)}')
print(f'Сумма элементов: {np.sum(M)}')
print(f'Стандартное отклонение: {np.std(M):.3f}')
print(f'Дисперсия: {np.var(M):.3f}')
print(f'Медиана: {np.median(M)}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
________________________________________

Минимальное значение:0
Максимальное значение:11
Среднее значение:5.5
Среднее значение в столбцах: [4. 5. 6. 7.]
Среднее значение в строках: [1.5 5.5 9.5]
Сумма элементов: 66
Стандартное отклонение: 3.452
Дисперсия: 11.917
Медиана: 5.5


___
## <h3 id='classic' style='color:red'> Методы классических массивов</h3>   
___

numpy<span style='color:red'>**.unique**</span> ( **array** ) - _`Возвращает массив уникальных элементов`_ объекта numpy **array**   
numpy<span style='color:red'>**.intersect1d**</span> ( **array_1**, **array_2** ) - _`Возвращает общие элементы`_ объектов numpy **array_1**  и **array_2**  
numpy<span style='color:red'>**.union1d**</span> ( **array_1**, **array_2** ) - _`Возвращает объединенный массив уникальных элементов`_ объектов numpy **array_1**  и **array_2**  
numpy<span style='color:red'>**.setfiff1d**</span> ( **array_1**, **array_2** ) - _`Возвращает уникальные элементы массива **array_1** `_ которых нет в массиве **array_2**  
numpy<span style='color:red'>**.setxor1d**</span> ( **array_1**, **array_2** ) - _`Возвращает не общие элементы массивов` **array_1** и **array_2**

In [30]:
a = np.array([1,1,2,2,3])
a1 = np.array([1,2,3])
a2 = np.array([2,3,4])
print(np.unique(a))
print(np.intersect1d(a1, a2))
print(np.union1d(a1, a2))
print(np.setdiff1d(a1, a2))
print(np.setxor1d(a1, a2))


[1 2 3]
[2 3]
[1 2 3 4]
[1]
[1 4]


  ---
## <h1 id='info' style='color:violet'> Информация о  массивах</h1>   
  ***

<span style='color:blue'>**.size**</span> - Возвращает _`количество элементов`_  **объекта** numpy   
<span style='color:blue'>**.itemsize**</span> - Возвращает _`размер элементовв байтах `_  **объекта** numpy  
<span style='color:blue'>**.ndim**</span> - Возвращает _`размерность`_  **объекта** numpy  
<span style='color:blue'>**.shape**</span> - Возвращает _`кол-во строк, кол-во столбцов`_  **объекта** numpy
___

In [31]:
M = np.zeros((3,5))
print(M)
print(M.itemsize)
print(M.size)
print(M.shape)
print(M.ndim)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
8
15
(3, 5)
2


<span style='color:blue'>**.dtype**</span> - Возвращает _`тип данных`_ элементов  **объекта** numpy   
___

In [32]:
arr = np.array([1, 2, 3], dtype=np.float64)
arr.dtype


dtype('float64')

numpy<span style='color:red'>**.isnan**</span>(arr) - Возвращает _`индексы`_ элементов со значением **`nan`** массива **arr** 

In [33]:
arr = np.array([np.nan, 1, 2, np.nan, 4])
print(f'True - для элементов с nan-значениями: {np.isnan(arr)}')

arr[np.isnan(arr)] = 0
print(f'Все элементы с nan-значениями заменены на 0: {arr}')


True - для элементов с nan-значениями: [ True False False  True False]
Все элементы с nan-значениями заменены на 0: [0. 1. 2. 0. 4.]


  ---
## <h1 id='import' style='color:violet'> Импорт/экспорт данных</h1>   
  ***

<span style='color:blue'>**.tolist**</span> - Экспортирует в _`спискок`_ элементы  **объекта** numpy   
___

In [34]:
import numpy as np

data = np.random.randint(0,10,(3,10))
list_data = data.tolist()
print(list_data)


[[4, 5, 7, 3, 6, 4, 3, 7, 6, 1], [3, 5, 8, 4, 6, 3, 9, 2, 0, 4], [2, 4, 1, 7, 8, 2, 9, 8, 7, 1]]


___
___
[ВВЕРХ](#comp)